const fs=require('fs');const p='T:/fars-wt/voices/src/audio/speech.ts';let s=fs.readFileSync(p,'utf8');
const rep=(a,b)=>{ if(!s.includes(a)) throw new Error('miss '+a.slice(0,60)); s=s.replace(a,b); };
rep("export interface SpeechRequest { ipa: string; lang?: LangId; voice: VoiceParams; intonation?: Intonation; lineId?: string; voiceKey?: string }",
"export interface SpeechRequest { ipa: string; lang?: LangId; voice: VoiceParams; intonation?: Intonation; lineId?: string; voiceKey?: string; /** D-336: the speaker's own neural voice (audio/neural/identity.ts); the NeuralBackend speaks with it */ neural?: NeuralVoice }");
rep("import type { LangId } from '../lang/lexicon';", "import type { LangId } from '../lang/lexicon';\nimport type { NeuralVoice } from './neural/identity';\nimport { voiceKey as neuralKey } from './neural/identity';\nimport { phonemesFor } from './neural/kokoro';\nimport type { NeuralVoices } from './neural/client';");
rep("/** Only same-origin relative paths: the pipeline must never call a network service. */",
"/** D-336 (UD-22): the person's own natural voice (Kokoro-82M in a worker: audio/neural). First in the chain: a request\n *  with the speaker's neural voice is spoken with it; without one (or before the model has loaded) the next backend speaks */\nexport class NeuralBackend implements VoiceBackend {\n  readonly id = 'kokoro';\n  constructor(readonly nv: NeuralVoices, readonly prio = 1) {}\n  async render(req: SpeechRequest): Promise<AudioClip | null> {\n    if (!req.neural || !this.nv.stats.ready) return null; const ph = phonemesFor(req.ipa, req.intonation); if (!ph) return null;\n    const r = await this.nv.say(req.neural, { phonemes: ph }, this.prio); if (!r || !r.pcm.length) return null;\n    return { sampleRate: r.rate, data: r.pcm, backend: this.id, tier: 'C' };\n  }\n}\n\n/** Only same-origin relative paths: the pipeline must never call a network service. */");
rep("private key(req: SpeechRequest) { const v = req.voice; return `${req.lineId ?? ''}|", "private key(req: SpeechRequest) { const v = req.voice; return `${req.neural ? neuralKey(req.neural) : ''}|${req.lineId ?? ''}|");
rep("say(line: SpeakableLine, voice: VoiceParams, pos: Vec3, opts: { speakerId?: string | number; voiceKey?: string; delay?: number; gain?: number } = {}): SpeechHandle {\n    return this.play({ ipa: line.ipa, lang: line.lang, voice, intonation: line.intonation, lineId: line.id, voiceKey: opts.voiceKey }, pos, line, opts);",
"say(line: SpeakableLine, voice: VoiceParams, pos: Vec3, opts: { speakerId?: string | number; voiceKey?: string; delay?: number; gain?: number; neural?: NeuralVoice } = {}): SpeechHandle {\n    return this.play({ ipa: line.ipa, lang: line.lang, voice, intonation: line.intonation, lineId: line.id, voiceKey: opts.voiceKey, neural: opts.neural }, pos, line, opts);");
fs.writeFileSync(p,s);
