const fs=require('fs');
let p='T:/fars-wt/voices/src/people/converse/ui.ts'; let s=fs.readFileSync(p,'utf8');
const rep=(a,b)=>{ if(!s.includes(a)) throw new Error('miss '+a.slice(0,80)); s=s.replace(a,b); };
rep("import { heardReply } from './voice';", "import { heardReply, heardReplyNeural, type HearIn } from './voice';\nimport { toFarsi, FarsiTranslator, type FarsiRoute } from './farsi';");
rep("interface Ctx { world: any; camera: THREE.Camera; clock: { dayIndex: number; localHour: number; t: number }; seed: number; englishVoice?: boolean }",
"interface Ctx { world: any; camera: THREE.Camera; clock: { dayIndex: number; localHour: number; t: number }; seed: number; englishVoice?: boolean; /** D-336: settings.hearIn (the opt-in layer) */ settings?: { hearIn?: HearIn } }");
rep("  let audio: AudioContext | null = null;", "  // D-336: the opt-in layer (settings.hearIn; ?hear=fa|en for tests) and the route of its Farsi (?farsi=llm|nllb; D-336 measured)\n  const hearIn = (): HearIn => (P.get('hear') as HearIn | null) ?? c.settings?.hearIn ?? 'own';\n  const faRoute = (): FarsiRoute => (P.get('farsi') as FarsiRoute | null) ?? FARSI_ROUTE; const nllb = new FarsiTranslator();\n  let audio: AudioContext | null = null;");
rep("export const NEAR_M = 3;", "export const NEAR_M = 3;\n/** D-336: the Farsi of the opt-in layer by default: the conversation model's own Persian of its reply (measured against NLLB-600M: DECISIONS D-336) */\nexport const FARSI_ROUTE: FarsiRoute = 'llm';");
rep("    if (a.ok) { const h = heardReply(sim.pop, near.pid, day, a.text, c.seed); heard = { lang: h.lang, units: h.units.map(u => u.translit || u.gloss), seconds: h.seconds };\n      play(h.data, h.rate); if (c.englishVoice || P.has('english')) { en ??= new EnglishVoice(); en.load().then(() => en!.say(a.text)).then(r => play(r.data, r.rate)).catch(() => {}); } }",
"    if (a.ok) {\n      // D-336 (UD-22): the person's own natural voice, in their own language, or (the opt-in layer) the same reply in Farsi or\n      // English; played at them in the world's sound (sayPcm), piece by piece as it renders\n      const nv = c.world.neural, agent = near.agent !== null ? sim.agents[near.agent] : null, layer = hearIn(); let fa: Awaited<ReturnType<typeof toFarsi>> = null;\n      if (layer === 'fa') fa = await toFarsi(a.text, { route: faRoute(), mind, nllb }).catch(() => null);\n      const faOk = !!fa && !fa.hits.length, key = near.agent !== null ? `a${near.agent}` : `p${near.pid}`, at = { x: near.e, y: c.camera.position.y - 0.1, z: -near.n };\n      const tH = performance.now();\n      const h = nv?.stats.ready ? await heardReplyNeural(nv, sim.pop, near.pid, day, a.text, c.seed, { hearIn: layer === 'fa' && !faOk ? 'en' : layer, farsi: faOk ? fa!.fa : null, agent,\n        onChunk: (pcm, rate) => { if (c.world.sayPcm) c.world.sayPcm(key, pcm, rate, at); else play(pcm, rate); } }) : null;\n      if (h) heard = { lang: h.lang, layer: h.layer, units: h.units.map(u => u.translit || u.gloss), text: h.text, seconds: h.seconds, backend: 'kokoro', firstMs: h.firstMs, afterTextMs: performance.now() - tH - h.seconds * 0 , fa: fa ? { route: fa.route, ms: fa.ms, hits: fa.hits } : null };\n      else { const f = heardReply(sim.pop, near.pid, day, a.text, c.seed, 24000, agent); heard = { lang: f.lang, layer: 'own', units: f.units.map(u => u.translit || u.gloss), seconds: f.seconds, backend: 'formant' }; play(f.data, f.rate); }\n      if (c.englishVoice || P.has('english')) { en ??= new EnglishVoice(); en.load().then(() => en!.say(a.text)).then(r => play(r.data, r.rate)).catch(() => {}); } }");
rep("heard: ${heard ? `${heard.lang} “${heard.units.join(' … ')}” (the person's own words, tier C: not a rendering of this English)` : 'nothing'}",
"heard: ${heard ? (heard.layer === 'own' ? `${heard.lang} “${heard.units.join(' … ')}” (the person's own words, tier C: not a rendering of this English)` : `${heard.layer === 'fa' ? 'Farsi' : 'English'} (opt-in, in their own voice): “${heard.text}”`) : 'nothing'}");
fs.writeFileSync(p,s);
