const fs=require('fs');
let p='T:/fars-wt/voices/src/audio/farcrowd.ts'; let s=fs.readFileSync(p,'utf8');
const rep=(a,b)=>{ if(!s.includes(a)) throw new Error('miss '+a.slice(0,80)); s=s.replace(a,b); };
rep("import type { Vec3 } from './speech';", "import type { Vec3 } from './speech';\nimport { unitsFor, voiceLang } from './voices';\nimport { neuralVoice, type NeuralVoice } from './neural/identity';\nimport type { NeuralVoices } from './neural/client';");
rep("interface Sector { s: NoiseStream;", "interface Sector { /** D-336: the next grain of a far talker's own voice */ nextGrain?: number; s: NoiseStream;");
rep("    const B = Array.from({ length: FAR_SECTORS }, () => ({ n: 0, x: 0, y: 0, z: 0, d: 0 }));", "    const B = Array.from({ length: FAR_SECTORS }, () => ({ n: 0, x: 0, y: 0, z: 0, d: 0, who: [] as NearPerson[] }));");
rep("      const b = B[FarCrowd.sectorOf(dx, dz)]; b.n++; b.x += p.x;", "      const b = B[FarCrowd.sectorOf(dx, dz)]; b.n++; if (b.who.length < 6) b.who.push(p); else if (((b.n * 2654435761) >>> 0) % b.n < 6) b.who[b.n % 6] = p; b.x += p.x;");
rep("  constructor(readonly e: AudioEngine, readonly nearR = 60) {}", "  constructor(readonly e: AudioEngine, readonly nearR = 60) {}\n  /** D-336 (UD-22): the far talkers' own voices: now and then a grain of one of them (a unit of theirs already rendered by the\n   *  neural voices, else its render queued at the lowest priority), through the sector's distance filter, over the murmur */\n  neural: NeuralVoices | null = null; private nv = new Map<string, NeuralVoice>(); grains = 0;");
rep("      // the syllabic flutter: a few voices rising and falling over the rest",
"      if (this.neural?.stats.ready && b.who.length && now >= (S.nextGrain ?? 0)) {\n        const p = b.who[Math.floor(this.rng.next() * b.who.length)], L = voiceLang(p.lang, p.langs).lang, U = L ? unitsFor(L) : null;\n        let v = this.nv.get(p.key); if (!v) { v = neuralVoice({ seed: p.seed, sex: p.sex, age: p.age, lang: p.lang }); if (this.nv.size > 4000) this.nv.clear(); this.nv.set(p.key, v); }\n        const pool = U ? [...U.lines, ...U.words] : [], u = pool.length ? pool[Math.floor(this.rng.next() * pool.length)] : null;\n        const pcm = u ? this.neural.get(v, u.id, u.ipa, u.intonation, 4) : null;\n        if (pcm) { const buf = c.createBuffer(1, pcm.length, 24000); buf.getChannelData(0).set(pcm); const src = c.createBufferSource(); src.buffer = buf; src.playbackRate.value = 0.97 + 0.06 * this.rng.next();\n          const gg = c.createGain(); gg.gain.value = 0.9 + 0.6 * this.rng.next(); src.connect(gg); gg.connect(S.lp); src.start(now + 0.02); src.stop(now + 0.05 + buf.duration * 1.05); this.grains++;\n          S.nextGrain = now + buf.duration * (0.5 + 0.7 * this.rng.next()) / Math.min(3, Math.max(1, Math.sqrt(b.n) / 2)); }\n        else S.nextGrain = now + 0.4 + 0.6 * this.rng.next(); }\n      // the syllabic flutter: a few voices rising and falling over the rest");
rep("(unintelligible murmur)`] : []; }", "(unintelligible murmur${this.neural?.stats.ready ? `, ${this.grains} grains of their own voices` : ''})`] : []; }");
fs.writeFileSync(p,s);
p='T:/fars-wt/voices/src/world/world.ts'; s=fs.readFileSync(p,'utf8');
rep("const voices = new PopulationVoices(audio, { seed }); voices.neural = neural;", "const voices = new PopulationVoices(audio, { seed }); voices.neural = neural; farCrowd.neural = neural;");
fs.writeFileSync(p,s);
console.log('ok');
