const fs=require('fs');
let p='T:/fars-wt/voices/tools/dev/voices_eval.ts'; let s=fs.readFileSync(p,'utf8');
const rep=(a,b)=>{ if(!s.includes(a)) throw new Error('miss '+a.slice(0,80)); s=s.replace(a,b); };
rep("export const SAME = 0.86;", "// the same-speaker thresholds: each embedding's equal-error threshold calibrated on this synthesiser's 54 speakers\n// (tools/dev/voices_calib.ts; WavLM-SV's published 0.86 is VoxCeleb's and does not hold here: every Kokoro voice scores\n// above it against every other, the first run of this tool)\nconst CAL = JSON.parse(readFileSync('REVIEWS/evidence/s12-voices/calib.json', 'utf8'));\nexport const SAME = CAL.models.ecapa.eer.t as number, SAME_W = CAL.models.wavlm.eer.t as number;");
rep("const tf: any = await import('@huggingface/transformers'); tf.env.allowRemoteModels = false;\nconst nllb = await tf.pipeline('translation', `${MODELS}/Xenova/nllb-200-distilled-600M/resolve/main`, { dtype: 'q8' });\n",
"// their Farsi: the replies' Persian (tools/dev/voices_fa_cache.ts; the text's quality is measured apart, D-336)\nconst FA = new Map<string, string>((JSON.parse(readFileSync(arg('--fa', 'REVIEWS/evidence/s12-voices/replies_fa.json'), 'utf8')).rows as any[]).map(r => [r.en, r.fa]));\nvoid MODELS;\n");
rep("  const own: Float32Array[] = [];\n  for (const j of replyJobs('own', units, english) as { phonemes: string }[]) own.push(await K.speak(j.phonemes, v));",
"  const own: Float32Array[] = [];\n  for (const j of replyJobs('own', units, english) as { phonemes: string }[]) own.push(await K.speak(j.phonemes, v));\n  // more of their own units (seeded) up to 6 s: an embedding of a second of speech is not the voice\n  { const U = lang ? unitsFor(lang as any) : { lines: [], words: WORDLESS }, pool = [...U.lines, ...U.words], rr = new Rng(id.seed >>> 0, 'voices.eval.more'); let sec = own.reduce((a, x) => a + x.length, 0) / 24000;\n    for (let k = 0; sec < 6 && k < 24 && pool.length; k++) { const u = pool[rr.int(0, pool.length - 1)]; const y = await K.speak(phonemesFor(u.ipa, u.intonation), v); own.push(y); sec += y.length / 24000; } }");
rep("  const fa = String((await nllb(english, { src_lang: 'eng_Latn', tgt_lang: 'pes_Arab', max_new_tokens: 120 }))[0].translation_text).trim();", "  const fa = FA.get(english) ?? '';");
rep("import { voiceLang } from '../../src/audio/voices';", "import { voiceLang, unitsFor, WORDLESS } from '../../src/audio/voices';\nimport { phonemesFor } from '../../src/audio/neural/kokoro';");
// uniqueness by ECAPA (calibrated); WavLM reported
rep("  let best = -1, who = -1, bestE = -1; for (const b of rows) if (b !== a) { const c = cos(F(a.emb), F(b.emb)); if (c > best) { best = c; who = b.pid; } bestE = Math.max(bestE, cos(F(a.ecapa), F(b.ecapa))); }\n  a.maxSim = +best.toFixed(4); a.nearest = who; a.maxSimEcapa = +bestE.toFixed(4); a.unique = best < SAME;",
"  let best = -1, who = -1, bestW = -1; for (const b of rows) if (b !== a) { const c = cos(F(a.ecapa), F(b.ecapa)); if (c > best) { best = c; who = b.pid; } bestW = Math.max(bestW, cos(F(a.emb), F(b.emb))); }\n  a.maxSim = +best.toFixed(4); a.nearest = who; a.maxSimWavlm = +bestW.toFixed(4); a.unique = best < SAME;");
rep("  for (const k of ['En', 'Fa'] as const) { const e = F(a['emb' + k]); const mine = cos(e, F(a.emb)); let other = -1; for (const b of rows) if (b !== a) other = Math.max(other, cos(e, F(b.emb)));",
"  for (const k of ['En', 'Fa'] as const) { const e = F(a['ecapa' + k]); const mine = cos(e, F(a.ecapa)); let other = -1; for (const b of rows) if (b !== a) other = Math.max(other, cos(e, F(b.ecapa)));");
rep("emb: Array.from(await I.wavlm(x)), ecapa: Array.from((await I.ecapa(x))!), embEn: Array.from(await I.wavlm(en16)), embFa: Array.from(await I.wavlm(fa16)),",
"emb: Array.from(await I.wavlm(x)), ecapa: Array.from((await I.ecapa(x))!), ecapaEn: Array.from((await I.ecapa(en16))!), ecapaFa: Array.from((await I.ecapa(fa16))!),");
rep("  rows: rows.map(({ emb, ecapa, embEn, embFa, ...x }) => x),", "  thresholds: { ecapa: SAME, wavlm: SAME_W, calib: CAL.models },\n  rows: rows.map(({ emb, ecapa, ecapaEn, ecapaFa, ...x }) => x),");
rep("maxSimMax: Math.max(...rows.map(x => x.maxSim)), maxSimMedian: rows.map(x => x.maxSim).sort((a, b) => a - b)[n >> 1], ecapaMaxSimMax: Math.max(...rows.map(x => x.maxSimEcapa)),",
"maxSimMax: Math.max(...rows.map(x => x.maxSim)), maxSimMedian: rows.map(x => x.maxSim).sort((a, b) => a - b)[n >> 1], wavlmMaxSimMax: Math.max(...rows.map(x => x.maxSimWavlm)),");
rep("status: 'measured: WavLM-SV embeddings, UTMOS22 as the MOS predictor (not a human listening panel: see the note)',", "status: 'measured: WeSpeaker ECAPA embeddings at the threshold calibrated on the synthesiser (WavLM-SV reported), UTMOS22 as the MOS predictor (not a human listening panel: see the note)',");
rep("embedding: 'Xenova/wavlm-base-plus-sv (threshold 0.86)', embedding2: 'Wespeaker/wespeaker-ecapa-tdnn512-LM (reported)',", "embedding: 'Wespeaker/wespeaker-ecapa-tdnn512-LM (threshold: calib.json equal-error point)', embedding2: 'Xenova/wavlm-base-plus-sv (reported; its VoxCeleb threshold 0.86 fails on synthetic speech)',");
fs.writeFileSync(p,s); console.log('ok');
