const fs=require('fs');
let p='T:/fars-wt/voices/tools/dev/voices_eval.ts'; let s=fs.readFileSync(p,'utf8');
const rep=(a,b)=>{ if(!s.includes(a)) throw new Error('miss '+a.slice(0,80)); s=s.replace(a,b); };
rep("const CAL = JSON.parse(readFileSync('REVIEWS/evidence/s12-voices/calib.json', 'utf8'));\nexport const SAME = CAL.models.ecapa.eer.t as number, SAME_W = CAL.models.wavlm.eer.t as number;",
"// (read when the scores are made: the calibration may still be running when the renders start)\nlet CAL: any = null, SAME = 0, SAME_W = 0;\nconst calib = async () => { const f = 'REVIEWS/evidence/s12-voices/calib.json'; while (!existsSync(f)) await new Promise(r => setTimeout(r, 30000));\n  CAL = JSON.parse(readFileSync(f, 'utf8')); SAME = CAL.models.ecapa.eer.t; SAME_W = CAL.models.wavlm.eer.t; };");
rep("import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';", "import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';");
rep("// ---- scores\n", "// ---- scores\nawait calib(); log('calibrated thresholds: ecapa', SAME, 'wavlm', SAME_W);\n");
fs.writeFileSync(p,s);
p='T:/fars-wt/voices/src/audio/neural/identity.ts'; s=fs.readFileSync(p,'utf8');
rep("/** the style voices a person may be blended from (D-336: measured on the lexicon's lines, tools/dev/voices_eval.ts\n *  --bases: the ones below the naturalness floor are left out) */\nexport const VOICE_POOL: { m: string[]; f: string[] } = {\n  m: BASE_VOICES.filter(v => v[1] === 'm').map(v => v[0]),\n  f: BASE_VOICES.filter(v => v[1] === 'f').map(v => v[0]),\n};",
"/** the style voices left out of the blends: below the naturalness floor on the period languages' lines (UTMOS22 mean of two\n *  sets of lines < 3.6, or English < 4.0, or Farsi < 3.7; tools/dev/voices_calib.ts, REVIEWS/evidence/s12-voices/calib.json).\n *  Mostly the voices trained on little data (the Spanish, French, Portuguese and Japanese ones) and the breathy or caricatured\n *  ones (af_nicole's whisper, the 'santa' voices) */\nexport const EXCLUDED = new Set(['af_bella', 'af_jessica', 'af_nicole', 'am_santa', 'bf_alice', 'bf_lily', 'bm_george', 'bm_lewis', 'ef_dora', 'em_alex', 'em_santa', 'ff_siwis',\n  'hm_omega', 'if_sara', 'jf_alpha', 'jf_gongitsune', 'jf_nezumi', 'jf_tebukuro', 'pf_dora', 'pm_alex', 'pm_santa', 'zf_xiaobei', 'zf_xiaoni', 'zf_xiaoxiao', 'zf_xiaoyi', 'zm_yunjian', 'zm_yunxi', 'zm_yunxia', 'zm_yunyang']);\n/** the style voices a person may be blended from */\nexport const VOICE_POOL: { m: string[]; f: string[] } = {\n  m: BASE_VOICES.filter(v => v[1] === 'm' && !EXCLUDED.has(v[0])).map(v => v[0]),\n  f: BASE_VOICES.filter(v => v[1] === 'f' && !EXCLUDED.has(v[0])).map(v => v[0]),\n};");
rep("export const OLDER = new Set(['am_santa', 'em_santa', 'pm_santa', 'bm_george', 'bm_lewis', 'am_onyx', 'hm_omega', 'bf_isabella', 'af_nicole']);", "export const OLDER = new Set(['am_onyx', 'bm_daniel', 'bm_fable', 'bf_isabella', 'af_river']);");
rep("/** voices that read as older (C, by ear and by the measured pitch: the \"santa\" voices, the deep British and American men) */", "/** voices that read as older (C: the deep British and American voices of the pool; with the older tract and pace) */");
rep("  Babylonian: ['es', 'pt', 'hi'], Syrian: ['es', 'pt'], Aramaic: ['es', 'pt'], Egyptian: ['pt', 'es', 'fr'],\n  Ionian: ['it', 'es', 'fr'], Greek: ['it', 'es', 'fr'], Lydian: ['it', 'fr'], Carian: ['it', 'pt'], Lycian: ['it', 'pt'], Thracian: ['fr', 'it'], Cappadocian: ['pt', 'hi'],",
"  Babylonian: ['it', 'hi'], Syrian: ['it', 'hi'], Aramaic: ['it', 'hi'], Egyptian: ['hi', 'it'],\n  Ionian: ['it', 'en-gb'], Greek: ['it', 'en-gb'], Lydian: ['it', 'en-gb'], Carian: ['it', 'en-gb'], Lycian: ['it', 'en-gb'], Thracian: ['en-gb', 'it'], Cappadocian: ['hi', 'it'],");
fs.writeFileSync(p,s); console.log('ok');
