const fs=require('fs');const p='T:/fars-wt/voices/src/audio/voices.ts';let s=fs.readFileSync(p,'utf8');
const rep=(a,b)=>{ if(!s.includes(a)) throw new Error('miss '+a.slice(0,80)); s=s.replace(a,b); };
rep("import { Rng, hashString } from '../core/rng';", "import { Rng, hashString } from '../core/rng';\nimport { neuralVoice, type NeuralVoice } from './neural/identity';\nimport { PRIO, type NeuralVoices } from './neural/client';");
rep("interface Slot { key: string; p: NearPerson; voice: VoiceParams;", "interface Slot { key: string; p: NearPerson; voice: VoiceParams; /** D-336: their own natural voice, and the unit waiting for its render */ nv: NeuralVoice; want?: { u: Unit; lang: LangId | null };");
rep("s = { key: p.key, p, voice: this.voiceOf(p), rng: r,", "s = { key: p.key, p, voice: this.voiceOf(p), nv: neuralVoice({ seed: p.seed, sex: p.sex, age: p.age, lang: p.lang }), rng: r,");
rep("renders: 0, renderMs: 0, starved: 0,", "renders: 0, renderMs: 0, starved: 0, /** D-336: utterances in the neural voices (the rest: formant) */ neural: 0, formant: 0,");
rep("  /** a baby's mean seconds between bouts of crying", "  /** D-336 (UD-22): the people's natural voices (Kokoro-82M in a worker); null or not yet loaded: the formant synthesiser\n   *  (PLACEHOLDER-QUALITY) speaks instead */\n  neural: NeuralVoices | null = null;\n  private bufs = new WeakMap<Float32Array, AudioBuffer>();\n  /** a baby's mean seconds between bouts of crying");
rep("const u = o.unit ?? this.pickUnit(s, lang, now); if (!u) return null;", "const u = o.unit ?? (s.want && s.want.lang === lang ? s.want.u : null) ?? this.pickUnit(s, lang, now); if (!u) return null;");
rep("    const buf = this.render(tune, lang ?? 'arc', v, s.n); if (!buf) return null;\n    const e = this.e, c = e.ctx!, p = s.p, t0 = now + 0.02, src = c.createBufferSource(); src.buffer = buf; src.playbackRate.value = 0.98 + 0.04 * s.rng.next();",
"    // D-336: the person's own natural voice when the model is up (the clip of this unit in their voice, cached; this\n    // utterance's pitch variation as the playback rate), else the formant synthesiser (placeholder)\n    const nv = this.neural?.stats.ready ? this.neural : null; let buf: AudioBuffer | null, shift = 1;\n    if (nv) {\n      const pcm = nv.get(s.nv, u.id, u.ipa, tune.intonation, kind === 'bed' ? PRIO.bed : d < 8 ? PRIO.near : PRIO.voice, u.kind === 'line' ? 0 : s.n & 1);\n      if (!pcm) { this.stats.starved++; this.stats.totalWaits++; if (!o.unit) s.want = { u, lang }; return null; }\n      s.want = undefined; buf = this.bufs.get(pcm) ?? null;\n      if (!buf) { buf = this.e.ctx!.createBuffer(1, pcm.length, 24000); buf.getChannelData(0).set(pcm); this.bufs.set(pcm, buf); }\n      shift = Math.max(0.8, Math.min(1.3, v.pitch / s.voice.pitch)); this.stats.neural++;\n    } else { buf = this.render(tune, lang ?? 'arc', v, s.n); if (buf) this.stats.formant++; }\n    if (!buf) return null;\n    const e = this.e, c = e.ctx!, p = s.p, t0 = now + 0.02, src = c.createBufferSource(); src.buffer = buf; src.playbackRate.value = (0.98 + 0.04 * s.rng.next()) * shift;");
rep("return [`voices (D-245, formant synth: PLACEHOLDER-QUALITY, C):", "const nv = this.neural?.stats.ready; return [`voices (D-245${nv ? '; D-336 natural voices, Kokoro-82M, one per person, C' : ', formant synth: PLACEHOLDER-QUALITY, C'}):");
fs.writeFileSync(p,s);
