const fs=require('fs');const p='T:/fars-wt/voices/src/world/world.ts';let s=fs.readFileSync(p,'utf8');
const rep=(a,b)=>{ if(!s.includes(a)) throw new Error('miss '+a.slice(0,80)); s=s.replace(a,b); };
rep("import { Speech, Subtitle, RecordingBackend, FormantBackend } from '../audio/speech';", "import { Speech, Subtitle, RecordingBackend, FormantBackend, NeuralBackend } from '../audio/speech';\nimport { NeuralVoices } from '../audio/neural/client';\nimport { neuralVoice } from '../audio/neural/identity';\nimport { voiceIdentity } from '../people/talkers';");
rep("  const speech = new Speech(audio, [new RecordingBackend(", "  // D-336 (UD-22): every person's own natural voice (Kokoro-82M in a worker, WebGPU or WASM; ?neural=0 keeps the formant\n  // synthesiser, which also speaks while the model loads or when it cannot): the scripted lines and the population's voices\n  const NP = typeof location !== 'undefined' ? new URLSearchParams(location.search) : new URLSearchParams();\n  const neural = NP.get('neural') !== '0' && typeof Worker !== 'undefined' ? new NeuralVoices({ device: (NP.get('neuraldevice') as 'webgpu' | 'wasm' | null) ?? undefined }) : null;\n  const speech = new Speech(audio, [...(neural ? [new NeuralBackend(neural)] : []), new RecordingBackend(");
rep("  const voices = new PopulationVoices(audio, { seed }); const nearBuf", "  const voices = new PopulationVoices(audio, { seed }); voices.neural = neural; const nearBuf");
rep("    const h = speech.say(line, vo, { x: a.pos[0], y: a.y + 1.55, z: -a.pos[1] }, { speakerId: a.id, voiceKey: key }); lastHandle = h;",
"    const vid = voiceIdentity(a, a.pid ?? -1, sim.pop, Math.floor(sim.t / 24), seed); // (the same identity as their murmur: crowd.ts voiceId)\n    const h = speech.say(line, vo, { x: a.pos[0], y: a.y + 1.55, z: -a.pos[1] }, { speakerId: a.id, voiceKey: key, neural: neuralVoice({ seed: vid.seed, sex: vid.sex, age: vid.age, lang: vid.lang }) }); lastHandle = h;");
rep("        ...voices.lines(), ...farCrowd.lines(),", "        ...voices.lines(), ...(neural?.lines() ?? ['neural voices off (?neural=0): formant synthesiser, PLACEHOLDER-QUALITY']), ...farCrowd.lines(),");
rep("people: { sim, crowd, nav, humans, view, geo, probe:", "neural, people: { sim, crowd, nav, humans, view, geo, probe:");
fs.writeFileSync(p,s);
