// The area registry (MASTER_PLAN §4.3, D-277): data/areas.json, generated by tools/dev/areas.ts from the physically walkable
// envelope. T-A6: the registry covers ≥ 99.5 % of the envelope; T-A6x: no unique area over 1 km², no interior over 0.25 ha;
// the count of unique areas and the area they cover never shrink without a DECISIONS row citing a user direction.
// The cover is checked twice: the generator's own figure, and here, independently, on seeded random points over the terrain
// rings (a point the controller can stand on must lie in some area), so a registry that trusts its own denominator fails.
// The registry must read the architecture, not a list: every building of buildTerrace and every site of buildTownPlan has
// its areas (a building added by D-276 fails this until the registry is regenerated: npm run areas).
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { AreaIndex, polyArea, inMulti, AREA_LIMIT_M2, INTERIOR_LIMIT_M2, type Registry } from '../tools/dev/lib/areas_geo';
import { terrainLayer, terrainAt, type TerrainLayer } from '../tools/dev/lib/envelope';
import { loadTerrain } from './plainLib';
import { buildTerrace } from '../src/arch/terrace';
import { Rng } from '../src/core/rng';
import type { Terrain } from '../src/terrain/heightfield';

const FILE = 'data/areas.json';
let reg: Registry, idx: AreaIndex, T: Terrain, L: TerrainLayer;
beforeAll(() => { reg = JSON.parse(readFileSync(FILE, 'utf8')); idx = new AreaIndex(reg); T = loadTerrain(); L = terrainLayer(T); });

describe('the area registry (data/areas.json)', () => {
  it('T-A6x: no unique area over 1 km², no interior over 0.25 ha (polygon areas recomputed here)', () => {
    const over = reg.areas.filter(a => a.role === 'unique').map(a => ({ id: a.id, m2: polyArea(a.shape), lim: a.interior ? INTERIOR_LIMIT_M2 : AREA_LIMIT_M2 })).filter(x => x.m2 > x.lim + 0.5);
    expect(over, 'unique areas over their limit').toEqual([]);
    for (const a of reg.areas) expect(Math.abs(polyArea(a.shape) - a.polyM2), a.id).toBeLessThan(2);
  });
  it('T-A6: the generator\'s cover of the envelope is ≥ 99.5 %, and its evidence says so', () => {
    expect(reg.meta.cover.pct).toBeGreaterThanOrEqual(99.5);
    const e = JSON.parse(readFileSync('REVIEWS/evidence/s10-instruments/T-A6.json', 'utf8'));
    expect(e).toMatchObject({ id: 'T-A6', tool: 'tools/dev/areas.ts' }); expect(e.value).toBeCloseTo(reg.meta.cover.pct, 3); expect(typeof e.dep).toBe('string');
    const x = JSON.parse(readFileSync('REVIEWS/evidence/s10-instruments/T-A6x.json', 'utf8'));
    expect(x).toMatchObject({ id: 'T-A6x', tool: 'tools/dev/areas.ts' }); expect(x.n).toBe(reg.areas.filter(a => a.role === 'unique').length);
  });
  it('T-A6, independently: seeded random points the controller can stand on (terrain slope ≤ 42°, reached) all lie in an area', () => {
    const R = new Rng(20260927, 'areas-test'), miss: number[][] = []; let n = 0;
    for (const [half, k] of [[71680, 3000], [10240, 1500], [2048, 1500]] as const) for (let i = 0; i < k; i++) {
      const e = R.range(-half, half), nn = R.range(-half, half), t = terrainAt(T, L, e, nn); if (!t.walk || !t.reach) continue; n++;
      if (!idx.all(e, nn).length) miss.push([Math.round(e), Math.round(nn)]); }
    expect(n).toBeGreaterThan(5000);
    expect(100 * (1 - miss.length / n), `uncovered points: ${JSON.stringify(miss.slice(0, 10))}`).toBeGreaterThanOrEqual(99.5);
  });
  it('the Terrace is judged building by building: every point on its platform has a unique Terrace area, and every building of buildTerrace has its areas', () => {
    const parts = buildTerrace().parts as any[], tp = parts.find(p => p.building === 'terrace' && p.kind === 'platform'), poly = [[tp.polygon.map((q: number[]) => [q[0], q[1]])]] as any;
    const xs = tp.polygon.map((q: number[]) => q[0]), ys = tp.polygon.map((q: number[]) => q[1]), R = new Rng(7, 'areas-terrace'); let n = 0;
    for (let i = 0; i < 3000 && n < 800; i++) { const e = R.range(Math.min(...xs), Math.max(...xs)), nn = R.range(Math.min(...ys), Math.max(...ys)); if (!inMulti(e, nn, poly)) continue; n++;
      const p = idx.primary(e, nn); expect(p?.kind ?? 'none', `(${e.toFixed(1)}, ${nn.toFixed(1)})`).toMatch(/^terrace-/); expect(p!.role).toBe('unique'); }
    const buildings = [...new Set(parts.map(p => p.building))].filter(b => b !== 'terrace').sort();
    expect(reg.meta.sources.buildings, 'the registry was generated from another Terrace: regenerate it (npm run areas)').toEqual(buildings);
    for (const b of buildings) expect(reg.areas.some(a => a.id.startsWith(`terrace:${b}:`)), b).toBe(true);
  });
  it('every town site, village and class member is an area, and each village and site centre lies in its own area', () => {
    for (const id of reg.meta.sources.town_sites) expect(idx.byId.has(`town:${id}`), id).toBe(true);
    for (const id of reg.meta.sources.villages) expect(idx.byId.has(`village:${id}`), id).toBe(true);
    for (const a of reg.areas.filter(a => a.kind === 'village' || a.kind === 'town-site')) { const [x0, y0, x1, y1] = a.bbox; expect(idx.all((x0 + x1) / 2, (y0 + y1) / 2).some(b => b.id === a.id), a.id).toBe(true); }
    for (const c of reg.classes) for (const m of c.members) expect(idx.byId.get(m)?.cls, m).toBe(c.id);
    expect(reg.areas.filter(a => a.kind === 'transect' && a.overlay).length).toBe(1);
  });
  it('the count of unique areas and the ground they cover never shrink without a DECISIONS row citing a UD', () => {
    const log = execFileSync('git', ['log', '--format=%H', '--', FILE], { encoding: 'utf8' }).trim().split('\n').filter(Boolean);
    const cur = { n: reg.meta.counts.unique as number, m2: reg.meta.totals.unique_union_m2 as number };
    const decisions = existsSync('DECISIONS.md') ? readFileSync('DECISIONS.md', 'utf8').split('\n') : [];
    const excused = decisions.some(l => /areas\.json/.test(l) && /shr[iu]nk/i.test(l) && /UD-\d+/.test(l));
    for (const h of log) { const old = JSON.parse(execFileSync('git', ['show', `${h}:${FILE}`], { encoding: 'utf8', maxBuffer: 1 << 28 }));
      if (excused) continue;
      expect(cur.n, `unique areas fell below ${h.slice(0, 8)}'s ${old.meta.counts.unique}`).toBeGreaterThanOrEqual(old.meta.counts.unique);
      expect(cur.m2, `unique ground fell below ${h.slice(0, 8)}'s ${old.meta.totals.unique_union_m2} m²`).toBeGreaterThanOrEqual(old.meta.totals.unique_union_m2 - 1); }
  });
});
