// Source data of the Cycles-rendered people impostors (D-331; tools/blender/impostors.mjs, BLENDER_PLAN row 19): every
// impostor dress (impostors.ts IMP_DRESSES) at FULL detail (outfits.ts LOD0: the D-322 simulated garments and the D-323
// strand cards, the costume the near crowd draws), on the dress's reference body (impostors.ts refVariant), in its typical
// pieces (typicalMask), posed by the game's own rig (humanRig.ts) in every frame of the atlas (impostors.ts FRAMES), with the
// carried jar and sack of the carrying frames (props.ts propGeometry: the modelled props, D-325). Written as .npy arrays in
// Blender's axes (x, -z, y) for tools/blender/people_impostors.py to render; nothing is shaped by hand in Blender.
//   npx tsx tools/blender/sources/people_imp_src.ts <out dir>
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { decodeHumanAssets, meshoptSimplify } from '../../../src/people/humanAssets';
import { buildOutfits, BUILT, COSTUMES, COSTUME_OF, unpackNormal, type Dress } from '../../../src/people/outfits';
import { readPeopleModels } from '../../../src/people/peopleModels';
import { IMP, IMP_DRESSES, FRAMES, solveFrame, typicalMask, slotOf, refVariant, xform, farLod } from '../../../src/people/impostors';
import { RigSolver, PALETTE_STRIDE } from '../../../src/people/humanRig';
import { HB, MAT, PRM_CARD } from '../../../src/people/humanFormat';
import { propGeometry } from '../../../src/people/props';
import { MeshoptSimplifier } from 'three/addons/libs/meshopt_simplifier.module.js';
import { loadModelsNode } from '../../../tests/lib/models_node';

const out = process.argv[2] ?? 'T:/fars-assets-s12/impostors/work/people/src'; mkdirSync(out, { recursive: true });
/** a .npy file (C order): float32 '<f4', uint32 '<u4', uint8 '|u1' */
function npy(path: string, a: Float32Array | Uint32Array | Uint8Array, shape: number[]) {
  const descr = a instanceof Float32Array ? '<f4' : a instanceof Uint32Array ? '<u4' : '|u1';
  let h = `{'descr': '${descr}', 'fortran_order': False, 'shape': (${shape.join(', ')}${shape.length === 1 ? ',' : ''}), }`;
  const tot = 10 + h.length + 1, pad = (64 - (tot % 64)) % 64; h = h + ' '.repeat(pad) + '\n';
  const head = Buffer.alloc(10); head[0] = 0x93; head.write('NUMPY', 1, 'latin1'); head[6] = 1; head[7] = 0; head.writeUInt16LE(h.length, 8);
  writeFileSync(path, Buffer.concat([head, Buffer.from(h, 'latin1'), Buffer.from(a.buffer, a.byteOffset, a.byteLength)]));
}
const t0 = performance.now();
const b = readFileSync('public/generated/humans/humans.bin');
const A = decodeHumanAssets(JSON.parse(readFileSync('public/generated/humans/humans.json', 'utf8')), b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength) as ArrayBuffer);
const M = readPeopleModels(f => { try { return readFileSync('public/' + f); } catch { return null; } });
if (!M.cards || !M.drape) throw new Error('people_hair / people_cloth missing: the impostors are rendered from the Blender garments and hair');
loadModelsNode();
await MeshoptSimplifier.ready;
const O = buildOutfits(A, { simplify: meshoptSimplify(MeshoptSimplifier), models: M, lods: [0, 1, 2] });
const CM = M.cards.meta;
const pg = (k: string) => { const g = propGeometry(k)!, n = g.getAttribute('position').count; return { pos: g.getAttribute('position').array as Float32Array, idx: g.index ? g.index.array : Array.from({ length: n }, (_, i) => i) }; };
const props = { jar: pg('jar'), sack: pg('sack') };
const meta: any = { about: 'generated by tools/blender/sources/people_imp_src.ts (D-331); do not edit', IMP, frames: FRAMES.map(f => f.id), dresses: [] as any[],
  hairAtlas: { file: CM.atlas.file, w: CM.atlas.w, h: CM.atlas.h, cols: CM.atlas.cols, rows: CM.atlas.rows.length } };
const rig = new RigSolver(A.meta.curlAxes), pal = new Float32Array(PALETTE_STRIDE);
for (const dress of IMP_DRESSES) {
  const L = (O.costumes[COSTUME_OF[dress]] ?? []).find(c => c.lod === 0); if (!L || !BUILT.includes(COSTUME_OF[dress])) { meta.dresses.push({ dress, missing: true }); continue; }
  const v = refVariant(A, dress), mask = typicalMask(dress), nv = L.tid.length;
  // the pieces the mask keeps (looks.ts: hairStyle from them: the bob straight, the court dresses in rows, the rest natural)
  const on = new Set(COSTUMES[COSTUME_OF[dress]].opt.filter((_, i) => (mask >> (i + 1)) & 1));
  const court = dress === 'persian' || dress === 'guard' || dress === 'median', hairStyle = on.has('hair_bob') ? 2 : court ? 1 : 0;
  // the triangles kept (all three corners in the mask), their colour slot (the first corner's, as the CPU bake) and card flag
  const keep = (i: number) => (mask >> L.hmat[i * 4 + 2]) & 1;
  const tri: number[] = []; for (let t = 0; t < L.index.length; t += 3) { const a = L.index[t], b2 = L.index[t + 1], c = L.index[t + 2]; if (keep(a) && keep(b2) && keep(c)) tri.push(a, b2, c); }
  const T = tri.length / 3, fslot = new Uint8Array(T), fcard = new Uint8Array(T);
  for (let t = 0; t < T; t++) { const a = tri[t * 3]; fslot[t] = slotOf(L.hmat[a * 4], L.hmat[a * 4 + 1]); fcard[t] = L.hmat[a * 4] === MAT.hair && L.hmat[a * 4 + 3] === PRM_CARD ? 1 : 0; }
  // the cards' strand-atlas coordinate per vertex (humanMaterial: the class's row for the hair style, the card's column;
  // v up in Blender's image space: 1 - v); -1 for the rest
  const cuv = new Float32Array(nv * 2).fill(-1);
  for (let i = 0; i < nv; i++) { if (!(L.hmat[i * 4] === MAT.hair && L.hmat[i * 4 + 3] === PRM_CARD)) continue;
    const cell = L.hext[i * 4 + 2], cls = cell >> 3, col = cell & 7, row = CM.classRows[cls]?.[hairStyle] ?? 0;
    const u = Math.min(0.996, Math.max(0.004, L.uv[i * 2])), w = Math.min(0.996, Math.max(0.004, L.uv[i * 2 + 1]));
    cuv[i * 2] = (col + u) / CM.atlas.cols; cuv[i * 2 + 1] = 1 - (row + w) / CM.atlas.rows.length; }
  const F = FRAMES.length, P = new Float32Array(F * nv * 3), N = new Float32Array(F * nv * 3), propFrames: any[] = [];
  FRAMES.forEach((Fr, fi) => {
    solveFrame(rig, pal, v.joints, Fr);
    for (let i = 0; i < nv; i++) { const t = (v.index * O.NV + L.tid[i]) * 4, bx = O.source[t], by = O.source[t + 1], bz = O.source[t + 2], n0 = unpackNormal(O.source[t + 3]);
      let px = 0, py = 0, pz = 0, qx = 0, qy = 0, qz = 0;
      for (let k = 0; k < 4; k++) { const w = L.skinWeight[i * 4 + k] / 255; if (!w) continue; const o = L.skinIndex[i * 4 + k] * 12;
        px += w * (pal[o] * bx + pal[o + 1] * by + pal[o + 2] * bz + pal[o + 3]); py += w * (pal[o + 4] * bx + pal[o + 5] * by + pal[o + 6] * bz + pal[o + 7]); pz += w * (pal[o + 8] * bx + pal[o + 9] * by + pal[o + 10] * bz + pal[o + 11]);
        qx += w * (pal[o] * n0[0] + pal[o + 1] * n0[1] + pal[o + 2] * n0[2]); qy += w * (pal[o + 4] * n0[0] + pal[o + 5] * n0[1] + pal[o + 6] * n0[2]); qz += w * (pal[o + 8] * n0[0] + pal[o + 9] * n0[1] + pal[o + 10] * n0[2]); }
      const ql = Math.hypot(qx, qy, qz) || 1, o = (fi * nv + i) * 3;
      P[o] = px; P[o + 1] = -pz; P[o + 2] = py; N[o] = qx / ql; N[o + 1] = -qz / ql; N[o + 2] = qy / ql; }
    const extra = Fr.prop === 'jar_head' ? xform(props.jar, rig.wt, HB.head, [0, 0.25, 0.02], 0.8) : Fr.prop === 'sack' ? xform(props.sack, rig.wt, HB.upperarm_r, [0.02, 0.13, -0.02], 1) : null;
    if (extra) { const n = extra.pos.length / 3, q = new Float32Array(n * 3); for (let i = 0; i < n; i++) { q[i * 3] = extra.pos[i * 3]; q[i * 3 + 1] = -extra.pos[i * 3 + 2]; q[i * 3 + 2] = extra.pos[i * 3 + 1]; }
      npy(`${out}/${dress}_prop${fi}_pos.npy`, q, [n, 3]); npy(`${out}/${dress}_prop${fi}_idx.npy`, Uint32Array.from(extra.idx as ArrayLike<number>), [extra.idx.length / 3, 3]); propFrames.push(fi); }
  });
  npy(`${out}/${dress}_pos.npy`, P, [F, nv, 3]); npy(`${out}/${dress}_nrm.npy`, N, [F, nv, 3]); npy(`${out}/${dress}_idx.npy`, Uint32Array.from(tri), [T, 3]);
  npy(`${out}/${dress}_fslot.npy`, fslot, [T]); npy(`${out}/${dress}_fcard.npy`, fcard, [T]); npy(`${out}/${dress}_cuv.npy`, cuv, [nv, 2]);
  const far = farLod(O, dress);
  meta.dresses.push({ dress, variant: v.meta.id, stature: v.height, verts: nv, tris: T, cards: fcard.reduce((s, x) => s + x, 0), hairStyle, pieces: [...on], propFrames, farTris: far ? far.index.length / 3 : 0 });
  console.log(`[people_imp_src] ${dress}: ${v.meta.id} ${nv} verts, ${T} tris (${meta.dresses.at(-1).cards} card tris), ${F} frames`);
}
writeFileSync(`${out}/meta.json`, JSON.stringify(meta, null, 1));
console.log(`[people_imp_src] done in ${((performance.now() - t0) / 1000).toFixed(1)} s -> ${out}`);
