// Source data of the Blender tree assets (D-327; tools/blender/trees.mjs): what the game's own generators produce, written
// as JSON for the Blender scripts, so nothing is shaped by hand in Blender (numbers before pictures):
//  - tiles: every leaf, blossom and twig tile of the leaf atlas as primitives (atlas.ts recordTiles: the same sprays, leaves
//    and flowers, at the same leaf fractions as the game's calibrated cards), for trees_atlas.py to model and render;
//  - models: every species variant's branch skeleton (model.ts buildModel: segments with end radii and branch level), for
//    trees_wood.py to skin into a bark-mapped mesh at the game's two levels of detail.
//   npx tsx tools/blender/sources/trees_src.ts <out.json>
import { writeFileSync } from 'node:fs';
import { allModels, M1, VARIANTS } from '../../../src/world/trees/model';
import { calibrateCards, leafFractions } from '../../../src/world/trees/kitdata';
import { recordTiles, buildAtlas, tileUV, COLS, ROWS, PAD, TILE, TILE_NAMES, HW_N, PALM_N } from '../../../src/world/trees/atlas';

const out = process.argv[2] ?? 'T:/fars-assets-s12/trees/work/src.json';
const models = calibrateCards(allModels());
const lf = leafFractions(models);
const tiles = recordTiles(lf);
// the procedural tiles' mean shade multiplier over their covered texels (atlas.ts shade 0.55 + 0.6 R): the Blender tiles are
// scaled to the same mean (trees.mjs), so a crown keeps the brightness its season colours (seasonal.ts) were tuned with
const proc = buildAtlas(lf), L0 = proc.levels[0];
const procMean = TILE_NAMES.map((_, ti) => { const { u, v } = tileUV(ti), ox = Math.round(u * proc.width), oy = Math.round(v * proc.height); let s = 0, n = 0;
  for (let j = 0; j < TILE; j++) for (let i = 0; i < TILE; i++) { const o = ((oy + j) * proc.width + ox + i) * 4; if (L0.data[o + 3] < 128) continue; s += 0.55 + 0.6 * L0.data[o] / 255; n++; }
  return n ? s / n : 1; });
const r6 = (x: number) => Math.round(x * 1e6) / 1e6;
const round = (v: any): any => typeof v === 'number' ? r6(v) : Array.isArray(v) ? v.map(round) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, round(x)])) : v;
const json = {
  about: 'generated by tools/blender/sources/trees_src.ts from src/world/trees (atlas.ts recordTiles, model.ts buildModel); do not edit',
  atlas: { cols: COLS, rows: ROWS, pad: PAD, names: TILE_NAMES, hw_n: HW_N, palm_n: PALM_N, leafFrac: round(lf), procMean: round(procMean), procFill: round(proc.fill) },
  tiles: tiles.map(t => ({ name: t.name, prims: round(t.prims) })),
  models: models.map((m, row) => ({ row, species: m.species.id, variant: m.variant, variants: VARIANTS, H: r6(m.H), W: r6(m.W), CB: r6(m.CB), bark: m.species.bark,
    lod1_segs: M1, segs: m.segs.slice(0, m.used.segs).map(s => round({ a: s.a, b: s.b, ra: s.ra, rb: s.rb, level: s.level })) })),
};
writeFileSync(out, JSON.stringify(json));
console.log(`[trees_src] ${out}: ${tiles.length} tiles, ${tiles.reduce((a, t) => a + t.prims.length, 0)} primitives (${tiles.map(t => `${t.name} ${t.prims.length}`).join(', ')}); ${models.length} models`);
