// D-310 dev probe (not shipped): ground_probe.ts plus the CC0 scanned classes (session 12): loose stones and boulders
// (groundRocks.ts), the ground flora (groundFlora.ts) and a row of the jars and baskets (furnish.ts, props.ts) at the viewer's feet
import * as THREE from 'three/webgpu';
import { loadScans } from '../../src/render/scans';
import { Terrain } from '../../src/terrain/heightfield';
import { TerrainMesh } from '../../src/terrain/terrainMesh';
import { bakeTerrainDetail } from '../../src/terrain/terrainDetail';
import { PlainGround } from '../../src/world/plain/terrainPlain';
import { buildZones } from '../../src/world/plain/fields';
import { loadRivers } from '../../src/world/plain/data';
import { buildCanals } from '../../src/world/plain/canals';
import { placeVillages } from '../../src/world/plain/villages';
import { buildRivers } from '../../src/world/plain/rivers';
import { canalBanks } from '../../src/world/plain/ribbons';
import { SEASON, BLOOM, WEATHER } from '../../src/render/materials';
import { seasonAt } from '../../src/world/season';
import { bloomAt, doyOf } from '../../src/world/plain/seasonal';
import { loadScanProps } from '../../src/render/scanProps';
import { GroundRocks } from '../../src/world/groundRocks';
import { GroundFlora } from '../../src/world/groundFlora';
import { jarGeometry } from '../../src/world/furnish';
import { propGeometry } from '../../src/people/props';
import type { CellCtx } from '../../src/world/smallLife';
import { Batch } from '../../src/world/settlement/geom';
import { scanShape } from '../../src/render/scanProps';
(async () => {
  const P = new URLSearchParams(location.search);
  const canvas = document.getElementById('c') as HTMLCanvasElement;
  const adapter = await (navigator as any).gpu.requestAdapter();
  const r = new THREE.WebGPURenderer({ canvas, antialias: true, requiredLimits: { maxSampledTexturesPerShaderStage: Math.min(48, adapter.limits.maxSampledTexturesPerShaderStage) } } as any); await r.init();
  r.toneMapping = THREE.AgXToneMapping; r.toneMappingExposure = +(P.get('xp') ?? 1);
  const errs: string[] = []; (r.backend as any).device?.addEventListener?.('uncapturederror', (e: any) => errs.push(String(e.error?.message).slice(0, 300)));
  await loadScans('/'); const ps = await loadScanProps('/'); (window as any).__props = ps;
  const terrain = await Terrain.load('/');
  const scene = new THREE.Scene(); scene.background = new THREE.Color(0.55, 0.68, 0.85);
  const tm = new TerrainMesh(terrain, 1); scene.add(tm.group);
  const rivers = await loadRivers(), canals = buildCanals(terrain, rivers.rivers, 1), villages = placeVillages(terrain, rivers.rivers, canals, 1);
  const zones = buildZones({ terrain, rivers: rivers.rivers.map(r => ({ x: r.x, y: r.y, halfCorridor: r.carveRadius.mid + 24 })), villages: villages.map(v => ({ x: v.x, y: v.y, r: v.r })) });
  const detail = await bakeTerrainDetail(terrain);
  const ground = new PlainGround(zones, detail);
  tm.group.traverse(o => { if ((o as THREE.Mesh).isMesh) (o as THREE.Mesh).material = ground.material; });
  const rv = buildRivers(terrain, rivers.rivers, canals); scene.add(rv.group); scene.add(canalBanks(canals, terrain));
  const hAt = (e: number, n: number) => terrain.heightAt(e, -n);
  const ctxAt = (e: number, n: number): CellCtx => { const sl = Math.hypot(hAt(e + 4, n) - hAt(e - 4, n), hAt(e, n + 4) - hAt(e, n - 4)) / 8; return sl > 0.3 ? 'rock' : P.get('ctx') === 'field' ? 'field' : 'steppe'; };
  const rocks = new GroundRocks(1, { ground: hAt, ctxAt } as any), flora = new GroundFlora(1, { ground: hAt, ctxAt } as any); scene.add(rocks.group, flora.group);
  const row = new THREE.Group(); scene.add(row);
  const clay = new THREE.MeshStandardNodeMaterial({ color: new THREE.Color(0.62, 0.44, 0.31), roughness: 0.85 }), vc = new THREE.MeshStandardNodeMaterial({ vertexColors: true, roughness: 0.85 });
  const pieces = [new THREE.Mesh(jarGeometry(0.17, 0.55, 40, 1), clay), new THREE.Mesh(jarGeometry(0.2, 0.6, 40, 2), clay), new THREE.Mesh(jarGeometry(0.13, 0.4, 32, 3), clay), new THREE.Mesh(propGeometry('jar')!, vc), new THREE.Mesh(propGeometry('basket')!, vc)];
  { const B = new Batch(); const sj = scanShape('jar', 0, [0.5, 0.72, 0.5], 0)!; B.geo(0, 0, 0, sj, 0.7, [0.4, 0.2, 0.12] as any); pieces.push(new THREE.Mesh(B.toGeometry(), vc)); }
  (window as any).__rowTris = pieces.map(m => (m.geometry.index ? m.geometry.index.count : m.geometry.getAttribute('position').count) / 3);
  const sun = new THREE.DirectionalLight(0xfff4e6, 3.2), hemi = new THREE.HemisphereLight(0xbfd6ff, 0x8a7458, 0.9);
  scene.add(sun, sun.target, hemi);
  const cam = new THREE.PerspectiveCamera(70, 16 / 9, 0.1, 60000);
  const dirOf = (az: number, alt: number) => { const psi = -((az - 341) * Math.PI) / 180, c = Math.cos(alt * Math.PI / 180); return new THREE.Vector3(-Math.sin(psi) * c, Math.sin(alt * Math.PI / 180), -Math.cos(psi) * c); };
  (window as any).__shot = async (v: { e: number; n: number; eye: number; az: number; pitch: number; fov: number; day: number; sunAz: number; sunAlt: number; wet?: number }) => {
    const ss = seasonAt(v.day); SEASON.green.value = ss.green; SEASON.dry.value = ss.dry; const bl = bloomAt(doyOf(v.day)); BLOOM.violet.value = bl.violet; BLOOM.yellow.value = bl.yellow; BLOOM.red.value = bl.red;
    WEATHER.wetness.value = v.wet ?? 0; WEATHER.puddles.value = Math.max(0, (v.wet ?? 0) - 0.4) / 0.6; ground.setDay(doyOf(v.day));
    const x = v.e, z = -v.n, g = terrain.heightAt(x, z);
    cam.position.set(x, g + v.eye, z); cam.rotation.set(v.pitch * Math.PI / 180, -((v.az - 341) * Math.PI) / 180, 0, 'YXZ'); cam.fov = v.fov; cam.updateProjectionMatrix(); cam.updateMatrixWorld();
    const d = dirOf(v.sunAz, v.sunAlt); sun.position.copy(cam.position).addScaledVector(d, 1000); sun.target.position.copy(cam.position);
    tm.update(cam.position); rocks.update([v.e, v.n]); flora.update(Math.floor(((v.day % 365) / 365) * 12 + 3) % 12, [v.e, v.n]);
    row.clear(); pieces.forEach((m, i) => { const a = (v.az - 341) * Math.PI / 180, fx = Math.sin(a), fz = -Math.cos(a), rx = Math.cos(a), rz = Math.sin(a), d = 2.2, off = (i - 2) * 0.55;
      const px = x + fx * d + rx * off, pz = z + fz * d + rz * off; m.position.set(px, terrain.heightAt(px, pz), pz); row.add(m); });
    (window as any).__stats = { rocks: rocks.stats, flora: flora.stats, scan: [...flora.scan.keys()] };
    for (let i = 0; i < 3; i++) await r.renderAsync(scene, cam);
    return errs.slice();
  };
  (window as any).__ready = true;
})().catch(e => { (window as any).__ready = String(e); console.error(e); });
