// PARSA (D-321): builds the dressed stone's block-face detail set.
//   node tools/blender/blockface.mjs [--device=GPU|CPU] [--no-bake] [--work=T:/fars-blender/blockface] [--check]
// 1. Blender, headless: tools/blender/blockface.py carves every layer of tools/blender/blockface.json and bakes its normals
//    and AO (Cycles; CPU by default: byte-reproducible; --device=GPU through the shared GPU slots);
// 2. KTX-Software: the layers as ONE 2-D array texture (RGBA8 linear, UASTC + zstd, mipmaps): public/textures/blockface/
//    blockface.ktx2 (one sampler in the shader for all of them: WebGPU's 16 samplers per fragment stage, B122);
// 3. src/data/blockface.json: the layer order, per-layer statistics the shader needs (AO mean, height scale), the strip
//    geometry, the input hash (spec + script: tests/blockface.test.ts recomputes it) and the output's sha256.
// --no-bake: re-encode from the PNGs already in the work dir. --check: exit 1 if the inputs changed since the last build.
import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '../..');
process.chdir(ROOT);
const args = process.argv.slice(2), flag = (k, d) => { const a = args.find(x => x.startsWith(`--${k}=`)); return a ? a.split('=')[1] : args.includes(`--${k}`) ? true : d; };
const DEVICE = flag('device', 'CPU'), WORK = flag('work', 'T:/fars-blender/blockface'), NOBAKE = !!flag('no-bake', false);
const BLENDER = process.env.BLENDER ?? 'C:/Program Files/Blender Foundation/Blender 5.0/blender.exe';
const KTX = process.env.KTX ?? ['C:/Program Files/KTX-Software/bin/ktx.exe', '/usr/local/bin/ktx'].find(p => existsSync(p)) ?? 'ktx';
const SLOT = process.env.GPU_SLOT_SCRIPT ?? 'C:/Users/Administrator/fars-assets/gpu_slot.mjs';
const SPEC = 'tools/blender/blockface.json', SCRIPT = 'tools/blender/blockface.py', OUT = 'public/textures/blockface/blockface.ktx2', META = 'src/data/blockface.json';
const log = (...a) => console.log('[blockface]', ...a);
export const blockfaceInputHash = (root = '.') => { const h = createHash('sha256'); for (const p of [SPEC, SCRIPT]) { const b = readFileSync(`${root}/${p}`); h.update(p); h.update('\0'); h.update(String(b.length)); h.update('\0'); h.update(b); } return h.digest('hex'); };
const inHash = blockfaceInputHash();
if (flag('check', false)) { const m = existsSync(META) ? JSON.parse(readFileSync(META, 'utf8')) : null; const ok = m?.inHash === inHash; log(ok ? 'current' : 'STALE'); process.exit(ok ? 0 : 1); }

const spec = JSON.parse(readFileSync(SPEC, 'utf8'));
mkdirSync(WORK, { recursive: true }); mkdirSync(dirname(OUT), { recursive: true });
const run = (cmd, argv) => { log('$', cmd, argv.join(' ')); const r = spawnSync(cmd, argv, { stdio: 'inherit' }); if (r.status !== 0) throw new Error(`${cmd} exited ${r.status}`); };
if (!NOBAKE) {
  const job = `${WORK}/job.json`;
  writeFileSync(job, JSON.stringify({ spec: resolve(SPEC), out_dir: WORK, device: DEVICE, only: null, preview: true }));
  const bl = [BLENDER, '-b', '--factory-startup', '--python', SCRIPT, '--', job];
  if (DEVICE === 'GPU') run('node', [SLOT, 'blockface-bake', '--', ...bl]); else run(bl[0], bl.slice(1));
}
const stats = JSON.parse(readFileSync(`${WORK}/blockface_stats.json`, 'utf8'));
const pngs = spec.layers.map(L => `${WORK}/${L.id}.png`);
for (const p of pngs) if (!existsSync(p)) throw new Error(`missing ${p}`);
// UASTC (quality 2) with RDO and zstd: the transcoder turns it into BC7 on desktop GPUs (1 byte per texel), the array's mips
// generated by the box filter (a normal map's mean slope, not a sharpened one)
run(KTX, ['create', '--format', 'R8G8B8A8_UNORM', '--assign-tf', 'linear', '--assign-primaries', 'none', '--layers', String(pngs.length),
  '--generate-mipmap', '--mipmap-filter', 'box', '--encode', 'uastc', '--uastc-quality', '2', '--uastc-rdo', '--zstd', '18', ...pngs, OUT]);
const out = readFileSync(OUT);
const meta = {
  about: 'Generated by tools/blender/blockface.mjs (D-321); do not edit. The block-face detail set: one KTX2 2-D array (public/textures/blockface/blockface.ktx2), RGBA = tangent normal x, y (OpenGL: x along u, y along v), 0.5 + h / hscale (mm), baked AO; each layer tiles over size_m; strip layers hold `strip_rows` rows of `strip_px` texels (v = mm from the arris).',
  res: spec.res, size_m: spec.size_m, strip_rows: spec.strip_rows, strip_px: spec.strip_px,
  layers: spec.layers.map(L => { const s = stats[L.id]; return { id: L.id, kind: L.kind, hscale: L.hscale, ao_mean: +s.ao_mean.toFixed(5), h_mean: +s.h_mean.toFixed(4), h_sd: +s.h_sd.toFixed(4), slope_sd: +s.slope_sd.toFixed(4), note: L.note }; }),
  inHash, outHash: createHash('sha256').update(out).digest('hex'), bytes: out.length, blender: stats._bake?.blender ?? '?', device: stats._bake?.device ?? DEVICE,
};
writeFileSync(META, JSON.stringify(meta, null, 1) + '\n');
log(`wrote ${OUT} (${(out.length / 1e6).toFixed(2)} MB) and ${META}`);
