// PARSA asset pipeline (D-305): one command regenerates every Blender-built asset from the project's own data.
//   node tools/blender/build.mjs [id ...] [--device=GPU|CPU] [--no-slot] [--verify] [--check] [--work=T:/fars-blender]
// For each asset of tools/blender/assets.json (or the ids given):
//  1. hashes its inputs (tools/blender/lib/inputs.mjs: the source script, the data and model files it reads, the SITE_SPEC
//     values, bake.py, the entry's settings);
//  2. writes its source meshes with the project's own code (npx tsx <source.script> <work> <args>);
//  3. bakes and exports in Blender, headless (tools/blender/bake.py); on the CPU by default (byte-reproducible: 3 of 3
//     --verify runs; the protome bakes in ~15 s on the 16 cores, no GPU slot), or on the T4 with --device=GPU (Cycles OptiX,
//     through the shared GPU slots, C:/Users/Administrator/fars-assets/gpu_slot.mjs; measured D-305: reproduced 1 of 2
//     builds, so a GPU-built asset may fail the reproducibility test: use it for bakes too heavy for the CPU);
//  4. KTX2: if the KTX-Software CLI (`ktx`) is on the PATH, re-encodes each map to KTX2 (UASTC + zstd, mipmaps) inside the
//     GLB (KHR_texture_basisu); otherwise the maps stay PNG and the manifest says so (textures: "png");
//  5. measures the GLB (triangles and vertices per level, image sizes, bytes, a GPU-memory estimate), checks the budgets,
//     copies it to public/models/<id>.glb and records the build in public/models/manifest.json;
//  6. copies three's Draco and Basis decoders into public/models/lib/ (the game serves them itself: src/render/models.ts).
// --verify: rebuild into the work dir only and compare the output hash with the manifest's (reproducibility).
// --check: only report which assets are stale (input hash differs from the manifest), exit 1 if any.
// Large intermediates live under the work dir (default T:/fars-blender, volatile; C: is small): nothing there is needed
// once public/models/ is written.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs';
import { execFileSync, spawnSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { measureGLB, repackGLB, sha256 } from './lib/glb.mjs';
import { readRegistry, inputHash } from './lib/inputs.mjs';
import { readPeopleRegistry, readPeopleManifest, peopleInputHash, buildPeopleAsset, recordPeople, writePeopleManifest } from './lib/people.mjs';

const ROOT = resolve(dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '../..');
process.chdir(ROOT);
const args = process.argv.slice(2), flag = (k, d) => { const a = args.find(x => x.startsWith(`--${k}=`)); return a ? a.split('=')[1] : args.includes(`--${k}`) ? true : d; };
const DEVICE = flag('device', 'CPU'), NOSLOT = !!flag('no-slot', false), VERIFY = !!flag('verify', false), CHECK = !!flag('check', false);
const WORK = flag('work', process.env.FARS_BLENDER_WORK ?? 'T:/fars-blender');
const BLENDER = process.env.BLENDER ?? 'C:/Program Files/Blender Foundation/Blender 5.0/blender.exe';
const SLOT = process.env.GPU_SLOT_SCRIPT ?? 'C:/Users/Administrator/fars-assets/gpu_slot.mjs';
const MANIFEST = 'public/models/manifest.json';
const REG = readRegistry(), ids = args.filter(a => !a.startsWith('--'));
const PREG = readPeopleRegistry(); // the people's assets (D-307: tools/blender/people.json, lib/people.mjs)
const want = ids.length ? ids.filter(i => !PREG.assets[i]) : Object.keys(REG.assets);
const wantPeople = ids.length ? ids.filter(i => PREG.assets[i]) : Object.keys(PREG.assets);
const pman = readPeopleManifest();
const manifest = existsSync(MANIFEST) ? JSON.parse(readFileSync(MANIFEST, 'utf8')) : { about: '', assets: {} };
manifest.about = 'Generated by tools/blender/build.mjs (D-305); do not edit. Per asset: the input hash (tools/blender/lib/inputs.mjs), the GLB and its sha256, measured triangles/vertices per level, maps, bytes, GPU estimate, texture format, the Blender version and device of the build.';
const log = (...a) => console.log('[blender]', ...a);

if (CHECK) {
  let stale = 0;
  for (const id of want) { const h = inputHash(id, REG.assets[id]), m = manifest.assets[id]; const ok = m?.inHash === h; if (!ok) stale++; log(id, ok ? 'current' : `STALE (manifest ${m?.inHash?.slice(0, 12) ?? 'none'}, inputs ${h.slice(0, 12)})`); }
  for (const id of wantPeople) { const h = peopleInputHash(id, PREG.assets[id]), m = pman.assets[id]; const ok = m?.inHash === h; if (!ok) stale++; log(id, ok ? 'current' : `STALE (manifest ${m?.inHash?.slice(0, 12) ?? 'none'}, inputs ${h.slice(0, 12)})`); }
  process.exit(stale ? 1 : 0);
}

const blenderVersion = (() => { try { return /Blender (\S+)/.exec(execFileSync(BLENDER, ['--version'], { encoding: 'utf8' }))?.[1] ?? '?'; } catch { throw new Error(`Blender not found at ${BLENDER} (set BLENDER=...)`); } })();
// the KTX-Software CLI: $KTX, else its installer's path (C:/Program Files/KTX-Software/bin, not on the PATH of every shell), else `ktx` on the PATH
const KTX = process.env.KTX ?? ['C:/Program Files/KTX-Software/bin/ktx.exe', '/usr/local/bin/ktx'].find(p => existsSync(p)) ?? 'ktx';
const ktx = (() => { const r = spawnSync(KTX, ['--version'], { encoding: 'utf8', shell: false }); return r.status === 0 ? r.stdout.trim() : null; })();
log(`Blender ${blenderVersion}; device ${DEVICE}${DEVICE === 'GPU' && !NOSLOT ? ' (through the GPU slots)' : ''}; KTX2 ${ktx ? ktx : 'unavailable (maps stay PNG)'}`);

function run(cmd, argv, opts = {}) {
  log('$', cmd, argv.join(' '));
  const r = spawnSync(cmd, argv, { stdio: 'inherit', ...opts });
  if (r.status !== 0) throw new Error(`${cmd} exited ${r.status}`);
}
const q = s => (/\s/.test(s) ? `"${s}"` : s);

let failed = 0;
for (const id of want) {
  const E = REG.assets[id]; if (!E) { console.error(`unknown asset ${id}`); failed++; continue; }
  const inHash = inputHash(id, E), work = `${WORK}/${id}`, src = `${work}/src`, out = `${work}/out`;
  mkdirSync(src, { recursive: true }); mkdirSync(out, { recursive: true });
  const t0 = Date.now();
  // 2. source meshes (the project's own model code)
  run(process.platform === 'win32' ? 'npx.cmd' : 'npx', ['tsx', E.source.script, src, ...E.source.args], { shell: process.platform === 'win32' });
  // 3. the Blender bake
  const job = { id, high: `${src}/high.ply`, lods: E.lods.map((L, i) => ({ ply: `${src}/lod${i}.ply`, tex: L.tex })), out_glb: `${out}/${id}.glb`, out_dir: out, device: DEVICE, bake: E.bake, seed: 0 };
  writeFileSync(`${work}/job.json`, JSON.stringify(job, null, 1));
  const bargs = ['-b', '--factory-startup', '--python', 'tools/blender/bake.py', '--', `${work}/job.json`];
  if (DEVICE === 'GPU' && !NOSLOT) run('node', [SLOT, 'blender', '--', q(BLENDER), ...bargs]); // gpu_slot spawns through a shell
  else run(BLENDER, bargs);
  const stats = JSON.parse(readFileSync(`${out}/bake_stats.json`, 'utf8'));
  let glb = readFileSync(job.out_glb), textures = 'png';
  // 4. KTX2 (only when the KTX-Software CLI is installed)
  if (ktx) {
    const M0 = measureGLB(glb), rep = {};
    for (const im of M0.images) {
      const png = `${out}/${id}_lod${im.index}.png`, k2 = png.replace(/\.png$/, '.ktx2');
      run(KTX, ['create', '--format', 'R8G8B8A8_UNORM', '--assign-tf', 'linear', '--encode', 'uastc', '--uastc-quality', '2', '--zstd', '18', '--generate-mipmap', png, k2]);
      rep[im.index] = { data: readFileSync(k2), mimeType: 'image/ktx2' };
    }
    glb = repackGLB(glb, rep); textures = 'ktx2';
  }
  // 5. measure, budgets, record
  const M = measureGLB(glb), B = E.budget, over = [];
  const lodNames = E.lods.map((_, i) => `lod${i}`);
  lodNames.forEach((n, i) => { const m = M.meshes[n]; if (!m) over.push(`${n} missing`); else if (m.tris > B.tris[i]) over.push(`${n} ${m.tris} tris > ${B.tris[i]}`); });
  M.images.forEach((im, i) => { if (im.w > B.tex[i] || im.h > B.tex[i]) over.push(`map ${i} ${im.w}x${im.h} > ${B.tex[i]}`); });
  if (M.bytes > B.glb_bytes) over.push(`GLB ${M.bytes} B > ${B.glb_bytes}`);
  if (M.gpuBytes > B.gpu_bytes) over.push(`GPU ${M.gpuBytes} B > ${B.gpu_bytes}`);
  const outHash = sha256(glb);
  if (over.length) { console.error(`[blender] ${id} OVER BUDGET: ${over.join('; ')}`); failed++; continue; }
  if (VERIFY) {
    const prev = manifest.assets[id]; const same = prev?.outHash === outHash;
    log(id, same ? `REPRODUCED: ${outHash.slice(0, 16)} equals the manifest's` : `DIFFERS: rebuilt ${outHash.slice(0, 16)}, manifest ${prev?.outHash?.slice(0, 16) ?? 'none'} (inputs ${prev?.inHash === inHash ? 'unchanged' : 'changed'})`);
    if (!same) failed++;
    else manifest.assets[id].reproduced = { outHash, device: stats.device, blender: blenderVersion }; // earned by this run, read by tests/blender_assets.test.ts
    continue;
  }
  mkdirSync('public/models', { recursive: true }); writeFileSync(`public/models/${id}.glb`, glb);
  manifest.assets[id] = {
    file: `models/${id}.glb`, inHash, outHash, bytes: M.bytes, gpuBytes: M.gpuBytes, textures,
    lods: lodNames.map((n, i) => ({ name: n, tris: M.meshes[n].tris, verts: M.meshes[n].verts, attrs: M.meshes[n].attrs, map: M.images[i] ? { w: M.images[i].w, h: M.images[i].h, format: M.images[i].format, bytes: M.images[i].bytes } : null,
      ao_mean: +stats.levels[i].ao_mean.toFixed(4) })),
    packing: 'normalTexture: RGB = tangent-space normal (MikkTSpace, OpenGL +Y), A = ambient occlusion (linear)',
    tier: E.tier, src: E.src, blender: blenderVersion, device: stats.device, bake_s: stats.seconds, build_s: Math.round((Date.now() - t0) / 1000),
  };
  log(id, `built in ${manifest.assets[id].build_s} s: ${M.bytes} B, GPU ~${(M.gpuBytes / 1e6).toFixed(1)} MB, ${lodNames.map(n => `${n} ${M.meshes[n].tris} tris`).join(', ')}; out ${outHash.slice(0, 16)}`);
}
if (VERIFY) writeFileSync(MANIFEST, JSON.stringify(manifest, null, 1) + '\n');
else {
  // 6. the decoders the game's loader uses, served from public/ (no CDN: COEP and offline play)
  const L = 'node_modules/three/examples/jsm/libs';
  for (const [d, files] of [['draco', ['draco_decoder.wasm', 'draco_wasm_wrapper.js', 'draco_decoder.js']], ['basis', ['basis_transcoder.js', 'basis_transcoder.wasm']]]) {
    mkdirSync(`public/models/lib/${d}`, { recursive: true }); for (const f of files) copyFileSync(`${L}/${d}/${f}`, `public/models/lib/${d}/${f}`);
  }
  // a rebuilt asset has not been reproduced yet (run --verify)
  const sorted = Object.fromEntries(Object.keys(manifest.assets).sort().map(k => [k, manifest.assets[k]]));
  writeFileSync(MANIFEST, JSON.stringify({ about: manifest.about, assets: sorted }, null, 1) + '\n');
}
// the people's assets (D-307): several files each (lib/people.mjs), their own manifest
for (const id of wantPeople) {
  const E = PREG.assets[id];
  try {
    const rep = buildPeopleAsset(id, E, { work: WORK, blender: BLENDER, ktx: ktx ? KTX : null, run, verify: VERIFY, device: DEVICE, slot: SLOT, noslot: NOSLOT, blenderVersion });
    if (rep.over.length) { console.error(`[blender] ${id} OVER BUDGET: ${rep.over.join('; ')}`); failed++; continue; }
    const ok = recordPeople(pman, rep, E, { verify: VERIFY, blenderVersion, ktxVersion: ktx });
    log(id, VERIFY ? (ok ? 'REPRODUCED: every file equals the manifest\'s' : 'DIFFERS from the manifest') : `built in ${rep.seconds} s: ${rep.bytes} B, GPU ~${(rep.gpuBytes / 1e6).toFixed(1)} MB; ${JSON.stringify(Object.fromEntries(Object.entries(rep.stats).map(([k, v]) => [k, v.tris ?? v])))}`);
    if (!ok) failed++;
  } catch (e) { console.error(`[blender] ${id} FAILED: ${e.message}`); failed++; }
}
if (wantPeople.length) writePeopleManifest(pman);
process.exit(failed ? 1 : 0);
