// PARSA (D-330): the decor and tents asset classes, built with Blender from the project's own data.
//   node tools/blender/decor.mjs [trim] [merlon] [tents] [--device=GPU|CPU] [--work=T:/fars-blender/decor] [--check]
//  trim:   the stone frames' trim texture (tools/blender/decor_trim.py; job from tools/blender/sources/frame_trim.ts):
//          public/models/decor/frame_trim.ktx2 (RGB normal, A AO; UASTC + zstd, mipmaps wrapping along u)
//  merlon: the four-stepped merlon, modelled worn and chipped and baked onto the game's merlon (tools/blender/decor_merlon.py;
//          low level from tools/blender/sources/merlon.ts): public/models/decor/merlon.glb
//  tents:  the court camps' tents, cloth-simulated on their poles with guy ropes and pegs (tools/blender/decor_tents.py; job
//          from tools/blender/sources/tents.ts): public/models/decor/tent_<kind>.glb, three levels each
// Records every build in src/data/decor_assets.json (input hash of the scripts and data, output sha256, sizes, stats), which
// src/render/decorAssets.ts and tests/decor_assets.test.ts read. --check: exit 1 if any input changed since its build.
import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '../..');
process.chdir(ROOT);
const args = process.argv.slice(2), flag = (k, d) => { const a = args.find(x => x.startsWith(`--${k}=`)); return a ? a.split('=')[1] : args.includes(`--${k}`) ? true : d; };
const DEVICE = flag('device', 'CPU'), WORK = flag('work', 'T:/fars-blender/decor');
const BLENDER = process.env.BLENDER ?? 'C:/Program Files/Blender Foundation/Blender 5.0/blender.exe';
const KTX = process.env.KTX ?? ['C:/Program Files/KTX-Software/bin/ktx.exe', '/usr/local/bin/ktx'].find(p => existsSync(p)) ?? 'ktx';
const SLOT = process.env.GPU_SLOT_SCRIPT ?? 'C:/Users/Administrator/fars-assets/gpu_slot.mjs';
const META = 'src/data/decor_assets.json', OUT = 'public/models/decor';
const log = (...a) => console.log('[decor]', ...a);
/** the inputs of each asset (their bytes decide staleness) */
export const DECOR_INPUTS = {
  trim: ['tools/blender/decor_trim.py', 'tools/blender/sources/frame_trim.ts', 'src/arch/frames.ts', 'src/data/site_spec.json'],
  merlon: ['tools/blender/decor_merlon.py', 'tools/blender/sources/merlon.ts', 'src/arch/decor.ts', 'src/data/site_spec.json'],
  tents: ['tools/blender/decor_tents.py', 'tools/blender/sources/tents.ts', 'src/world/tentForms.ts', 'src/people/camps.ts'],
};
export const decorInputHash = (id, root = '.') => { const h = createHash('sha256'); for (const p of DECOR_INPUTS[id]) { const b = existsSync(`${root}/${p}`) ? readFileSync(`${root}/${p}`) : Buffer.alloc(0); h.update(p); h.update('\0'); h.update(String(b.length)); h.update('\0'); h.update(b); } return h.digest('hex'); };
const sha = b => createHash('sha256').update(b).digest('hex');
const meta = existsSync(META) ? JSON.parse(readFileSync(META, 'utf8')) : { about: '', assets: {} };
meta.about = 'Generated by tools/blender/decor.mjs (D-330); do not edit. Per asset: the input hash (DECOR_INPUTS), the output files with their sha256 and bytes, and the build\'s statistics.';
const want = args.filter(a => !a.startsWith('--')); const ids = want.length ? want : Object.keys(DECOR_INPUTS);
if (flag('check', false)) { let stale = 0; for (const id of ids) { const ok = meta.assets[id]?.inHash === decorInputHash(id); if (!ok) stale++; log(id, ok ? 'current' : 'STALE'); } process.exit(stale ? 1 : 0); }

const run = (cmd, argv, opts = {}) => { log('$', cmd, argv.join(' ')); const r = spawnSync(cmd, argv, { stdio: 'inherit', ...opts }); if (r.status !== 0) throw new Error(`${cmd} exited ${r.status}`); };
const npx = (argv) => run(process.platform === 'win32' ? 'npx.cmd' : 'npx', ['tsx', ...argv], { shell: process.platform === 'win32' });
const blender = (script, argv, label) => { const bl = ['-b', '--factory-startup', '--python', script, '--', ...argv]; if (DEVICE === 'GPU') run('node', [SLOT, label, '--', `"${BLENDER}"`, ...bl]); else run(BLENDER, bl); };
const ktx2 = (png, out, wrap = 'wrap') => run(KTX, ['create', '--format', 'R8G8B8A8_UNORM', '--assign-tf', 'linear', '--encode', 'uastc', '--uastc-quality', '2', '--zstd', '18', '--generate-mipmap', '--mipmap-wrap', wrap, png, out]);
mkdirSync(OUT, { recursive: true });

for (const id of ids) {
  const work = `${WORK}/${id}`; mkdirSync(work, { recursive: true }); const t0 = Date.now(), inHash = decorInputHash(id);
  if (id === 'trim') {
    npx(['tools/blender/sources/frame_trim.ts', `${work}/job.json`]);
    blender('tools/blender/decor_trim.py', [`${work}/job.json`, work, DEVICE], 'decor-trim');
    const st = JSON.parse(readFileSync(`${work}/frame_trim_stats.json`, 'utf8'));
    ktx2(`${work}/frame_trim.png`, `${OUT}/frame_trim.ktx2`);
    const b = readFileSync(`${OUT}/frame_trim.ktx2`);
    meta.assets.trim = { inHash, files: { 'models/decor/frame_trim.ktx2': { sha256: sha(b), bytes: b.length } }, stats: st, build_s: Math.round((Date.now() - t0) / 1000) };
  } else if (id === 'merlon') {
    npx(['tools/blender/sources/merlon.ts', work]);
    blender('tools/blender/decor_merlon.py', [`${work}/job.json`, work, DEVICE], 'decor-merlon');
    const st = JSON.parse(readFileSync(`${work}/merlon_stats.json`, 'utf8'));
    const { repackGLB, measureGLB } = await import('./lib/glb.mjs');
    let glb = readFileSync(`${work}/merlon.glb`); const M0 = measureGLB(glb), rep = {};
    for (const im of M0.images) { const png = `${work}/merlon_lod${im.index}.png`, k2 = png.replace(/\.png$/, '.ktx2'); ktx2(png, k2, 'clamp'); rep[im.index] = { data: readFileSync(k2), mimeType: 'image/ktx2' }; }
    glb = repackGLB(glb, rep); writeFileSync(`${OUT}/merlon.glb`, glb); const M = measureGLB(glb);
    meta.assets.merlon = { inHash, files: { 'models/decor/merlon.glb': { sha256: sha(glb), bytes: glb.length } }, lods: Object.fromEntries(Object.entries(M.meshes).map(([k, m]) => [k, { tris: m.tris, verts: m.verts }])), gpuBytes: M.gpuBytes, stats: st, build_s: Math.round((Date.now() - t0) / 1000) };
  } else if (id === 'tents') {
    npx(['tools/blender/sources/tents.ts', work]);
    blender('tools/blender/decor_tents.py', [`${work}/job.json`, work, DEVICE], 'decor-tents');
    const st = JSON.parse(readFileSync(`${work}/tents_stats.json`, 'utf8'));
    const { repackGLB, measureGLB } = await import('./lib/glb.mjs'); const files = {}, lods = {};
    for (const kind of st.kinds) {
      let glb = readFileSync(`${work}/tent_${kind}.glb`); const M0 = measureGLB(glb), rep = {};
      for (const im of M0.images) { const png = `${work}/tent_${kind}_map${im.index}.png`, k2 = png.replace(/\.png$/, '.ktx2'); ktx2(png, k2, 'clamp'); rep[im.index] = { data: readFileSync(k2), mimeType: 'image/ktx2' }; }
      glb = repackGLB(glb, rep); writeFileSync(`${OUT}/tent_${kind}.glb`, glb); const M = measureGLB(glb);
      files[`models/decor/tent_${kind}.glb`] = { sha256: sha(glb), bytes: glb.length }; lods[kind] = Object.fromEntries(Object.entries(M.meshes).map(([k, m]) => [k, { tris: m.tris, verts: m.verts }]));
    }
    meta.assets.tents = { inHash, files, lods, stats: st, build_s: Math.round((Date.now() - t0) / 1000) };
  } else throw new Error(`unknown decor asset ${id}`);
  log(id, `built in ${meta.assets[id].build_s} s`, JSON.stringify(meta.assets[id].files));
}
// the decoders the loader uses (as build.mjs: served from public/models/lib/)
const L = 'node_modules/three/examples/jsm/libs';
for (const [d, files] of [['draco', ['draco_decoder.wasm', 'draco_wasm_wrapper.js', 'draco_decoder.js']], ['basis', ['basis_transcoder.js', 'basis_transcoder.wasm']]]) {
  mkdirSync(`public/models/lib/${d}`, { recursive: true }); for (const f of files) if (!existsSync(`public/models/lib/${d}/${f}`)) copyFileSync(`${L}/${d}/${f}`, `public/models/lib/${d}/${f}`);
}
const sorted = Object.fromEntries(Object.keys(meta.assets).sort().map(k => [k, meta.assets[k]]));
writeFileSync(META, JSON.stringify({ about: meta.about, assets: sorted }, null, 1) + '\n');
