// PARSA impostor assets (D-331; BLENDER_PLAN row 19): the far people's atlas rendered in Blender/Cycles from the full-detail
// people (the D-322 garments and D-323 strand cards), replacing the CPU bake of the far bodies (src/people/impostors.ts,
// which stays as the fallback when the atlas is absent, stale or fails to load):
//   src     npx tsx tools/blender/sources/people_imp_src.ts: every impostor dress x frame posed at full detail (npy) and the
//           strand atlas transcoded to PNG (KTX-Software)
//   render  tools/blender/people_impostors.py: Cycles, four emission passes per dress (weights, normal, occlusion + depth)
//   post    npx tsx tools/blender/sources/people_imp_post.ts: the game's layout, mips, KTX2 -> public/models/impostors/
//   manifest public/models/impostors/manifest.json: input hash, output hashes and sizes
//   node tools/blender/impostors.mjs [src] [render] [post] [manifest]   (none: all)  [--spp=64] [--device=GPU|CPU]
// Heavy Cycles renders go through tools/dev/gpu_slot.mjs when --device=GPU (the watchdog: at most two heavy GPU jobs).
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { impInputHash } from './lib/imp_inputs.mjs';

const BLENDER = process.env.BLENDER ?? 'C:/Program Files/Blender Foundation/Blender 5.0/blender.exe';
const KTX = process.env.KTX ?? ['C:/Program Files/KTX-Software/bin/ktx.exe', '/usr/local/bin/ktx'].find(p => existsSync(p)) ?? 'ktx';
const WORK = process.env.IMP_WORK ?? 'T:/fars-assets-s12/impostors/work/people', GAME = 'public/models/impostors';
const args = process.argv.slice(2), flag = (k, d) => { const a = args.find(x => x.startsWith(`--${k}=`)); return a ? a.split('=')[1] : d; };
const steps = args.filter(a => !a.startsWith('--')), want = s => !steps.length || steps.includes(s);
const SPP = flag('spp', '64'), DEVICE = flag('device', 'GPU'), SRC = `${WORK}/src`, REN = `${WORK}/render`;
mkdirSync(WORK, { recursive: true }); mkdirSync(GAME, { recursive: true });
const t0 = Date.now(), log = (...a) => console.log(`[impostors ${((Date.now() - t0) / 1000).toFixed(0)}s]`, ...a);
const run = (cmd, argv, label) => { const r = spawnSync(cmd, argv, { stdio: 'inherit', shell: false }); if (r.status !== 0) throw new Error(`${label} exited ${r.status}`); };
const tsx = (script, argv, label) => run(process.execPath, ['node_modules/tsx/dist/cli.mjs', script, ...argv], label);

if (want('src')) {
  tsx('tools/blender/sources/people_imp_src.ts', [SRC], 'people_imp_src');
  run(KTX, ['extract', '--transcode', 'rgba8', 'public/models/people/people_hair_atlas.ktx2', `${SRC}/hair_atlas.png`], 'ktx extract');
}
if (want('render')) {
  const bl = [BLENDER, '-b', '--factory-startup', '--python', 'tools/blender/people_impostors.py', '--', SRC, REN, SPP, DEVICE];
  if (DEVICE === 'GPU') run(process.execPath, ['tools/dev/gpu_slot.mjs', 'impostors-people', '--', ...bl.map(q => q.includes(' ') ? `"${q}"` : q)], 'render');
  else run(bl[0], bl.slice(1), 'render');
}
if (want('post')) tsx('tools/blender/sources/people_imp_post.ts', [SRC, REN, `${WORK}/post`, GAME], 'people_imp_post');
if (want('manifest')) {
  const idx = JSON.parse(readFileSync(`${GAME}/people_impostors.json`, 'utf8')), files = {};
  for (const f of ['people_impostors.json', ...Object.values(idx.files).map(o => o.file)]) { const b = readFileSync(`${GAME}/${f}`); files[f] = { sha256: createHash('sha256').update(b).digest('hex'), bytes: b.length }; }
  const man = { about: 'Generated by tools/blender/impostors.mjs (D-331); do not edit. The people impostor atlas: its input hash (impInputHash), each file with sha256 and size, GPU bytes.',
    assets: { people_impostors: { inHash: impInputHash({ spp: SPP, device: DEVICE }), settings: { spp: SPP, device: DEVICE }, files, bytes: Object.values(files).reduce((s, f) => s + f.bytes, 0), gpuBytes: idx.gpuBytes, built: new Date().toISOString().slice(0, 10) } } };
  writeFileSync(`${GAME}/manifest.json`, JSON.stringify(man, null, 1) + '\n');
  log('manifest', (man.assets.people_impostors.bytes / 1e6).toFixed(2), 'MB');
}
log('done');
