// The hills' bedrock pieces (session 12, D-335): CC0 Poly Haven scans (T:/fars-assets-s12/models/polyhaven/<id>/2k; url,
// licence and sha256 of every raw file in T:/fars-assets-s12/models/manifest.json) -> public/models/land/<class>.glb (Draco,
// three levels per piece) + <class>_{diff,nor,arm}.jpg (a 2x2 atlas per class) + manifest.json (what src/world/hills/rockKit.ts
// loads). Run: node tools/blender/land_rocks.mjs   (Blender headless, tools/blender/land_rocks.py; ~5 min)
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, statSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';

const SRC = process.env.SRC ?? 'T:/fars-assets-s12/models/polyhaven';
const BLENDER = process.env.BLENDER ?? 'C:/Program Files/Blender Foundation/Blender 5.0/blender.exe';
const WORK = process.env.WORK ?? 'T:/fars-assets-s12/land/rocks';
const OUT = 'public/models/land';
const src = id => `${SRC}/${id}/2k/${id}.gltf`;
/** the classes (up to four sources each: the atlas cells) and their pieces. `ledge`: the resistant beds standing as low cliffs
 *  along the strata (front faces downhill); `ground`: outcrops, slabs and scree lying on the slope (tilted to the ground) */
export const CLASSES = {
  // (the ledges, D-335 round 1, were scanned cliff pieces (namaqualand_cliff_02, rock_face_01, mountainside, coastal_cliff_04)
  // placed along the risers: in the probe they stood as isolated boxes and tombstones on a smooth slope, not as beds; the
  // ledges are now continuous strips faced with a baked cliff, src/world/hills/ledges.ts and land_ledgeface.py)
  ground: [
    { id: 'outcrop05', src: src('coast_rocks_05'), flat: true, segs: 1, lods: [3000, 600, 80] },     // an outcrop boulder on its bedrock
    { id: 'slab02', src: src('coast_land_rocks_02'), flat: true, segs: 1, lods: [2500, 500, 60] },   // a low bedrock outcrop
    { id: 'talus03', src: src('coast_land_rocks_03'), flat: true, segs: 1, lods: [3000, 600, 80] },  // talus: blocks in their scree
    { id: 'scree04', src: src('coast_land_rocks_04'), flat: true, segs: 1, lods: [2000, 400, 50] },  // a scree and gravel apron
  ],
};
mkdirSync(WORK, { recursive: true }); mkdirSync(OUT, { recursive: true });
for (const c of Object.values(CLASSES)) for (const s of c) if (!existsSync(s.src)) throw new Error(`missing download ${s.src}`);
const job = { out: WORK, tex: 1024, classes: CLASSES };
writeFileSync(`${WORK}/job.json`, JSON.stringify(job));
if (!process.env.NOBLEND) {
  const r = spawnSync(BLENDER, ['-b', '--factory-startup', '--python', 'tools/blender/land_rocks.py', '--', `${WORK}/job.json`], { stdio: 'inherit' });
  if (r.status !== 0) throw new Error(`blender exited ${r.status}`);
}
const rawMan = existsSync('T:/fars-assets-s12/models/manifest.json') ? JSON.parse(readFileSync('T:/fars-assets-s12/models/manifest.json', 'utf8')) : null;
const man = { about: 'Generated by tools/blender/land_rocks.mjs (D-335); do not edit. CC0 1.0 scans from Poly Haven (polyhaven.com), cut, oriented, decimated to three levels (lod0/lod1/lod2), Draco; maps packed per class into a 2x2 atlas (JPEG). Raw downloads with sha256: T:/fars-assets-s12/models/manifest.json.', classes: {} };
const sha = f => createHash('sha256').update(readFileSync(f)).digest('hex');
for (const cls of Object.keys(CLASSES)) {
  const info = JSON.parse(readFileSync(`${WORK}/${cls}.json`, 'utf8'));
  const files = [`${cls}.glb`, `${cls}_diff.jpg`, `${cls}_nor.jpg`, `${cls}_arm.jpg`];
  for (const f of files) copyFileSync(`${WORK}/${f}`, `${OUT}/${f}`);
  man.classes[cls] = { licence: 'CC0-1.0', source: 'Poly Haven', files: Object.fromEntries(files.map(f => [f, { bytes: statSync(`${OUT}/${f}`).size, sha256: sha(`${OUT}/${f}`) }])),
    sources: CLASSES[cls].map(s => { const id = s.src.split('/').at(-1).replace('.gltf', ''); return { id, url: `https://polyhaven.com/a/${id}`, raw: rawMan ? Object.keys(rawMan.files ?? rawMan).filter(k => k.includes(id)).length + ' raw files in the download manifest' : null }; }),
    pieces: info.pieces };
}
writeFileSync(`${OUT}/manifest.json`, JSON.stringify(man, null, 1));
console.log('land rocks:', Object.entries(man.classes).map(([k, v]) => `${k}: ${v.pieces.length} pieces, ${(Object.values(v.files).reduce((s, f) => s + f.bytes, 0) / 1e6).toFixed(1)} MB`).join('; '));
