// CC0 scanned props (session 12, D-310): converts the Poly Haven downloads (T:/fars-assets-s12/models/polyhaven/<id>/2k,
// see T:/fars-assets-s12/models/manifest.json for url + sha256 of every raw file) into public/models/props/<id>.glb
// (Draco, two levels, JPEG maps at `tex`) and public/models/props/manifest.json (what src/render/scanProps.ts loads).
//   node tools/blender/ph_props.mjs [id ...]      (SRC=... to point at another download root)
import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';

const SRC = process.env.SRC ?? 'T:/fars-assets-s12/models/polyhaven';
const BLENDER = process.env.BLENDER ?? 'C:/Program Files/Blender Foundation/Blender 5.0/blender.exe';
const OUT = 'public/models/props';
/** the chosen assets: role (what they stand for in the world), triangle targets per level, map size */
export const PROPS = {
  // rocks and stones of the plain and the hills (the Kuh-e Rahmat limestone; the scans are sandstone/granite from
  // Namaqualand and elsewhere: the grain is kept, the albedo is re-tinted to the measured rock palette at runtime)
  stone_01: { role: 'stone', lod0: 600, lod1: 120, tex: 512 },
  rock_07: { role: 'stone', lod0: 700, lod1: 140, tex: 512 },
  rock_09: { role: 'stone', lod0: 500, lod1: 100, tex: 512 },
  namaqualand_stones_01: { split: true, role: 'stone', lod0: 900, lod1: 200, tex: 512 },
  namaqualand_rocks_01: { split: true, role: 'stone', lod0: 1200, lod1: 250, tex: 1024 },
  namaqualand_boulder_02: { role: 'boulder', lod0: 2500, lod1: 400, tex: 1024 },
  namaqualand_boulder_03: { role: 'boulder', lod0: 2500, lod1: 400, tex: 1024 },
  namaqualand_boulder_04: { role: 'boulder', lod0: 2500, lod1: 400, tex: 1024 },
  namaqualand_boulder_05: { role: 'boulder', lod0: 2000, lod1: 350, tex: 1024 },
  namaqualand_boulder_06: { role: 'boulder', lod0: 2000, lod1: 350, tex: 1024 },
  rock_face_02: { role: 'outcrop', lod0: 3000, lod1: 500, tex: 1024 },
  // ground flora
  shrub_02: { split: true, role: 'cushion', lod0: 2500, lod1: 500, tex: 1024 },
  shrub_04: { role: 'camelthorn', lod0: 2000, lod1: 400, tex: 1024 },
  shrub_03: { split: true, role: 'camelthorn', lod0: 1500, lod1: 300, tex: 1024 },
  weed_plant_02: { split: true, role: 'thistle', lod0: 1500, lod1: 300, tex: 512 },
  nettle_plant: { split: true, role: 'thistle', lod0: 1500, lod1: 300, tex: 512 },
  dry_branches_medium_01: { split: true, role: 'deadwood', lod0: 1200, lod1: 250, tex: 512 },
  // vessels and containers
  ceramic_vase_01: { weld: true, role: 'jar', lod0: 1500, lod1: 400, tex: 1024 },
  ceramic_vase_04: { weld: true, role: 'jar', lod0: 1500, lod1: 400, tex: 1024 },
  antique_ceramic_vase_01: { weld: true, role: 'jar', lod0: 1500, lod1: 400, tex: 1024 },
  ceramic_pot: { weld: true, role: 'pot', lod0: 1200, lod1: 250, tex: 1024 },
  planter_pot_clay: { weld: true, role: 'pot', lod0: 1000, lod1: 200, tex: 512 },
  wicker_basket_01: { weld: true, remesh1: true, role: 'basket', lod0: 1500, lod1: 300, tex: 1024 },
  wicker_basket_02: { weld: true, role: 'basket', lod0: 1500, lod1: 300, tex: 1024 },
  wooden_crate_02: { weld: true, role: 'crate', lod0: 1200, lod1: 250, tex: 1024 },
  wooden_bowl_01: { weld: true, role: 'bowl', lod0: 800, lod1: 160, tex: 512 },
};
const want = process.argv.slice(2).filter(a => !a.startsWith('--'));
const ids = want.length ? want : Object.keys(PROPS);
mkdirSync(OUT, { recursive: true });
const WORK = process.env.WORK ?? 'T:/fars-assets-s12/models/work'; mkdirSync(WORK, { recursive: true });
const jobs = ids.map(id => ({ id, src: `${SRC}/${id}/2k/${id}.gltf`, out: `${WORK}/${id}.glb`, lod0: PROPS[id].lod0, lod1: PROPS[id].lod1, tex: PROPS[id].tex, split: !!PROPS[id].split, weld: !!PROPS[id].weld, remesh1: !!PROPS[id].remesh1 }));
for (const j of jobs) if (!existsSync(j.src)) throw new Error(`missing download ${j.src}`);
writeFileSync(`${WORK}/jobs.json`, JSON.stringify(jobs));
const r = spawnSync(BLENDER, ['-b', '--factory-startup', '--python', 'tools/blender/ph_props.py', '--', `${WORK}/jobs.json`], { stdio: 'inherit' });
if (r.status !== 0) throw new Error(`blender exited ${r.status}`);
const MAN = `${OUT}/manifest.json`;
const man = want.length && existsSync(MAN) ? JSON.parse(readFileSync(MAN, 'utf8')) : { about: '', assets: {} };
man.about = 'Generated by tools/blender/ph_props.mjs (D-310); do not edit. CC0 scans from Poly Haven (polyhaven.com), decimated to two levels (lod0, lod1), Draco, JPEG maps. Raw downloads with sha256: T:/fars-assets-s12/models/manifest.json (branch assets-archive).';
for (const id of ids) for (const k of Object.keys(man.assets)) if (k === id || man.assets[k].of === id) delete man.assets[k];
for (const info of JSON.parse(readFileSync(`${WORK}/jobs.json.out.json`, 'utf8'))) {
  const buf = readFileSync(info.file), P = PROPS[info.of];
  writeFileSync(`${OUT}/${info.id}.glb`, buf);
  man.assets[info.id] = { file: `models/props/${info.id}.glb`, of: info.of, role: P.role, licence: 'CC0 1.0', source: `https://polyhaven.com/a/${info.of}`, bytes: buf.length, sha256: createHash('sha256').update(buf).digest('hex'), srcTris: info.src_tris, tris: info.tris, size_m: info.size_m, tex: info.tex };
}
writeFileSync(MAN, JSON.stringify(man, null, 1) + '\n');
console.log('[ph_props]', Object.keys(man.assets).length, 'assets;', Object.values(man.assets).reduce((s, a) => s + a.bytes, 0) / 1e6, 'MB');
