// dev (D-277; MASTER_PLAN §4.2 "Session budget ... measured, not assumed"): gates/budget.json, the measured timings of the
// render lane and the renderless throughput, each with its source, and what they imply for Tier 1 (T-B3: a full rotation
// within 4 sessions) given the area registry. A figure nobody has measured is null with the reason; nothing is assumed.
// Usage: npx tsx tools/dev/lib/budget.ts   (re-run when a new measurement lands: edit MEASURED with its source)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

/** every figure with its source; null = not measured (and why) */
export const MEASURED = {
  t_world_build_s: { value: 17, src: 'D-250 (tools/dev/trace_load.mjs, idle box, test quality): settlement 6.1 s, architecture 2.5 s, plain 2.6 s, impostors 1.5 s' },
  t_load_s: { idle: 35, busy: 244, src: 'CLAUDE.md working rules, session 8 (tools/dev/load_probe.mjs): load time is contention' },
  t_first_frames_compile_s: { value: 300, range: [298, 318], src: 'D-250: first render 88 s, then 210-230 s more as streamed content draws for the first time (SwiftShader pipeline compiles)' },
  t_test_s: { value: 285, src: 'REVIEWS/coverage_report.md: median wall time per coverage view at test quality 960×540 (tests/e2e/coverage.spec.ts, session-9 pilot, loaded box)' },
  t_high_s: { per_frame: [150, 240], per_view: 480, src: 'CLAUDE.md working rules, session 8: a high frame 2.5-4 min, a high view test ~8 min (queue waits of ~50 min not included)' },
  t_id_s: { value: null, why: 'no ID-and-depth-only pass exists yet (MASTER_PLAN §4.2 480×270 ID pass: TO-BUILD)' },
  t_ultra_s: { value: null, why: 'no ultra view has been timed on this box' },
  renderless: {
    node_offline_bot_hours_per_core_hour: { value: 6.6, src: 'REVIEWS/evidence/s9-town-walk/walkers_run_51e6ae6.txt: tools/dev/walkers.ts, offline node world with people, one nice-15 process on a loaded box: town 200.6 bot-min in 1,828 s, compounds 83.4 bot-min in 754 s (6.6× real time each)' },
    chromium_norender_bot_hours_per_core_hour: { value: null, why: 'the ?norender page (D-253) has not been driven by bots with a throughput measurement; §6 step 2 asks for it with Tier-1 jobs running' },
    two_core_real_time_factor: { value: 13.2, src: 'node_offline × 2 slots (tools/dev/cpu_slot.sh), assuming no contention between the two: to be measured with both slots busy' },
  },
  offline_tools_s: {
    areas: { value: 899 as number | null, src: 'tools/dev/areas.ts, session 10, one cpu slot under load 4-6: world 26 s, 144k town/village boxes 6 s, terrain layer 1 s, 92 patches 624 s (the Terrace-town cluster 6,679 buckets, 27 M cells: 250 s), areas and two envelope passes 240 s; ~4 GB' },
    tier0: { value: null as number | null, src: 'REVIEWS/evidence/s10-instruments/tier0.json meta.run_s' },
  },
};

export function budget() {
  const reg = existsSync('data/areas.json') ? JSON.parse(readFileSync('data/areas.json', 'utf8')) : null;
  const th = JSON.parse(readFileSync('gates/thresholds.json', 'utf8')).thresholds as any[], get = (id: string) => th.find(r => r.id === id);
  const nA0 = get('T-A0')?.sample_min ?? 59, nA0t = get('T-A0t')?.sample_min ?? 150;
  const M = structuredClone(MEASURED) as any;
  if (existsSync('REVIEWS/evidence/s10-instruments/tier0.json')) M.offline_tools_s.tier0.value = JSON.parse(readFileSync('REVIEWS/evidence/s10-instruments/tier0.json', 'utf8')).meta?.run_s ?? null;
  let derived: any = { why: 'data/areas.json absent' };
  if (reg) {
    const uniq = reg.areas.filter((a: any) => a.role === 'unique' && !a.overlay).length;
    // classes: at least 8 views per member in classes of ≤ 50 members, else stratified so every member tile is hit (≥ n A0 over the class)
    const cls = reg.classes.map((c: any) => ({ id: c.id, members: c.members.length, n: c.members.length <= 50 ? Math.max(nA0, 8 * c.members.length) : Math.max(nA0, c.members.length) }));
    const views = uniq * nA0 + nA0t + cls.reduce((s: number, c: any) => s + c.n, 0), perSession = Math.ceil(views / 4), laneHours = +(perSession * MEASURED.t_test_s.value / 3600).toFixed(1);
    derived = { tier1_views_per_rotation: views, unique_areas: uniq, per_unique_area: nA0, transect: nA0t, classes: cls, tier1_views_per_session_for_T_B3: perSession,
      lane_hours_per_session_at_t_test: laneHours, note: `At the measured ${MEASURED.t_test_s.value} s a test view, holding T-B3 (a rotation in 4 sessions) needs ${laneHours} render-lane hours a session: T-B3 fails unless the per-view cost falls (ID passes at 480×270, grouped loads) or the lane grows; MASTER_PLAN §4.2 says the rotation target is never raised.` };
  }
  return { about: 'The session budget (MASTER_PLAN §4.2): measured timings with their sources, null where not measured. Generated by tools/dev/lib/budget.ts; do not edit by hand (edit MEASURED there with a source).', measured: M, derived };
}
if (process.argv[1]?.endsWith('budget.ts')) { const b = budget(); writeFileSync('gates/budget.json', JSON.stringify(b, null, 1) + '\n'); console.log(`gates/budget.json: Tier 1 needs ${b.derived.tier1_views_per_session_for_T_B3} views a session (${b.derived.lane_hours_per_session_at_t_test} lane-hours)`); }
