// dev (D-277; MASTER_PLAN axis J, T-J1a, T-J1b, T-J2): data/event_kinds.json, the vocabulary the novelty count uses: every
// event kind the world's calendar can make (src/data/events_calendar.json), the place classes (the area registry's kinds,
// data/areas.json) and the states (MASTER_PLAN axis B: the eight hour bands and nine weathers, and the four seasons). A
// "triple" is (event kind × place class × state); T-J1a counts new triples per bot-hour. Rare-tail kinds (T-J2) are the ones
// the calendar makes at most a few times a year (per_1000_per_year, once, trigger, state rules, or a mean rate under one a
// month), marked here for the walkers to count. Generated; do not edit.
// Usage: npx tsx tools/dev/lib/event_kinds.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { HOUR_BANDS, WEATHERS } from '../coverage_time';

export function eventKinds() {
  const cal = JSON.parse(readFileSync('src/data/events_calendar.json', 'utf8')), reg = JSON.parse(readFileSync('data/areas.json', 'utf8'));
  const rare = (r: any) => ['per_1000_per_year', 'once', 'trigger', 'state'].includes(r?.type) || (r?.type === 'rate' && ((r.per === 'year') || (r.per === 'month' && (r.mean ?? 1) < 1)));
  const kinds = cal.events.filter((e: any) => e.rule?.type !== 'never').map((e: any) => ({ id: e.id, kind: e.kind, name: e.name, place: e.place_kind ?? null, rule: e.rule?.type ?? null, tier: e.tier ?? null, rare_tail: rare(e.rule) }));
  const never = cal.events.filter((e: any) => e.rule?.type === 'never').map((e: any) => ({ id: e.id, name: e.name, why: e.note ?? '' }));
  const placeClasses = [...new Set(reg.areas.map((a: any) => a.kind as string))].sort();
  const states = { hour_bands: [...HOUR_BANDS], weathers: [...WEATHERS], seasons: ['spring', 'summer', 'autumn', 'winter'] };
  const nStates = states.hour_bands.length * states.weathers.length * states.seasons.length;
  return { about: 'Event kinds × place classes × states for the novelty measures (MASTER_PLAN axis J: T-J1a, T-J1b, T-J2). Generated by tools/dev/lib/event_kinds.ts from src/data/events_calendar.json and data/areas.json; do not edit.',
    source: { calendar: 'src/data/events_calendar.json', registry: 'data/areas.json' }, kinds, excluded_never: never, place_classes: placeClasses, states,
    counts: { kinds: kinds.length, event_kinds: [...new Set(kinds.map((k: any) => k.kind))].length, rare_tail: kinds.filter((k: any) => k.rare_tail).length, place_classes: placeClasses.length, states: nStates, triples_possible: kinds.length * placeClasses.length * nStates },
    note: 'The calendar holds the scheduled and triggered kinds; incidents that emerge from system state (T-F4) are not in it yet and join this list when tools/dev/systems_probe.ts exists.' };
}
if (process.argv[1]?.endsWith('event_kinds.ts')) { const o = eventKinds(); writeFileSync('data/event_kinds.json', JSON.stringify(o, null, 1) + '\n'); console.log(`data/event_kinds.json: ${o.counts.kinds} kinds (${o.counts.rare_tail} rare-tail), ${o.counts.place_classes} place classes, ${o.counts.states} states`); }
